/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt Containerized Data Importer API
 * Containerized Data Importer for KubeVirt.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Flags will create a patch that will replace all flags for the container's command field. The only flags that will be used are those define. There are no guarantees around forward/backward compatibility.  If set incorrectly this will cause the resource when rolled out to error until flags are updated.
 * @export
 * @interface V1beta1Flags
 */
export interface V1beta1Flags {
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof V1beta1Flags
   */
  api?: { [key: string]: string };
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof V1beta1Flags
   */
  controller?: { [key: string]: string };
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof V1beta1Flags
   */
  uploadProxy?: { [key: string]: string };
}
