/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt Containerized Data Importer API
 * Containerized Data Importer for KubeVirt.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V1beta1CustomizeComponentsPatch,
    V1beta1CustomizeComponentsPatchFromJSON,
    V1beta1CustomizeComponentsPatchFromJSONTyped,
    V1beta1CustomizeComponentsPatchToJSON,
    V1beta1Flags,
    V1beta1FlagsFromJSON,
    V1beta1FlagsFromJSONTyped,
    V1beta1FlagsToJSON,
} from './';

/**
 * CustomizeComponents defines patches for components deployed by the CDI operator.
 * @export
 * @interface V1beta1CustomizeComponents
 */
export interface V1beta1CustomizeComponents {
    /**
     * 
     * @type {V1beta1Flags}
     * @memberof V1beta1CustomizeComponents
     */
    flags?: V1beta1Flags;
    /**
     * 
     * @type {Array<V1beta1CustomizeComponentsPatch>}
     * @memberof V1beta1CustomizeComponents
     */
    patches?: Array<V1beta1CustomizeComponentsPatch>;
}

export function V1beta1CustomizeComponentsFromJSON(json: any): V1beta1CustomizeComponents {
    return V1beta1CustomizeComponentsFromJSONTyped(json, false);
}

export function V1beta1CustomizeComponentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1beta1CustomizeComponents {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'flags': !exists(json, 'flags') ? undefined : V1beta1FlagsFromJSON(json['flags']),
        'patches': !exists(json, 'patches') ? undefined : ((json['patches'] as Array<any>).map(V1beta1CustomizeComponentsPatchFromJSON)),
    };
}

export function V1beta1CustomizeComponentsToJSON(value?: V1beta1CustomizeComponents | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'flags': V1beta1FlagsToJSON(value.flags),
        'patches': value.patches === undefined ? undefined : ((value.patches as Array<any>).map(V1beta1CustomizeComponentsPatchToJSON)),
    };
}

