/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt Containerized Data Importer API
 * Containerized Data Importer for KubeVirt.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V1ObjectMeta,
    V1ObjectMetaFromJSON,
    V1ObjectMetaFromJSONTyped,
    V1ObjectMetaToJSON,
    V1beta1UploadTokenRequestSpec,
    V1beta1UploadTokenRequestSpecFromJSON,
    V1beta1UploadTokenRequestSpecFromJSONTyped,
    V1beta1UploadTokenRequestSpecToJSON,
    V1beta1UploadTokenRequestStatus,
    V1beta1UploadTokenRequestStatusFromJSON,
    V1beta1UploadTokenRequestStatusFromJSONTyped,
    V1beta1UploadTokenRequestStatusToJSON,
} from './';

/**
 * UploadTokenRequest is the CR used to initiate a CDI upload
 * @export
 * @interface V1beta1UploadTokenRequest
 */
export interface V1beta1UploadTokenRequest {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof V1beta1UploadTokenRequest
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof V1beta1UploadTokenRequest
     */
    kind?: string;
    /**
     * 
     * @type {V1ObjectMeta}
     * @memberof V1beta1UploadTokenRequest
     */
    metadata: V1ObjectMeta;
    /**
     * 
     * @type {V1beta1UploadTokenRequestSpec}
     * @memberof V1beta1UploadTokenRequest
     */
    spec: V1beta1UploadTokenRequestSpec;
    /**
     * 
     * @type {V1beta1UploadTokenRequestStatus}
     * @memberof V1beta1UploadTokenRequest
     */
    status: V1beta1UploadTokenRequestStatus;
}

export function V1beta1UploadTokenRequestFromJSON(json: any): V1beta1UploadTokenRequest {
    return V1beta1UploadTokenRequestFromJSONTyped(json, false);
}

export function V1beta1UploadTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1beta1UploadTokenRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'metadata': V1ObjectMetaFromJSON(json['metadata']),
        'spec': V1beta1UploadTokenRequestSpecFromJSON(json['spec']),
        'status': V1beta1UploadTokenRequestStatusFromJSON(json['status']),
    };
}

export function V1beta1UploadTokenRequestToJSON(value?: V1beta1UploadTokenRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'apiVersion': value.apiVersion,
        'kind': value.kind,
        'metadata': V1ObjectMetaToJSON(value.metadata),
        'spec': V1beta1UploadTokenRequestSpecToJSON(value.spec),
        'status': V1beta1UploadTokenRequestStatusToJSON(value.status),
    };
}

