/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt Containerized Data Importer API
 * Containerized Data Importer for KubeVirt.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  V1ObjectMeta,
  V1beta1DataImportCronSpec,
  V1beta1DataImportCronStatus,
} from './';

/**
 * DataImportCron defines a cron job for recurring polling/importing disk images as PVCs into a golden image namespace
 * @export
 * @interface V1beta1DataImportCron
 */
export interface V1beta1DataImportCron {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   * @type {string}
   * @memberof V1beta1DataImportCron
   */
  apiVersion?: string;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   * @type {string}
   * @memberof V1beta1DataImportCron
   */
  kind?: string;
  /**
   *
   * @type {V1ObjectMeta}
   * @memberof V1beta1DataImportCron
   */
  metadata?: V1ObjectMeta;
  /**
   *
   * @type {V1beta1DataImportCronSpec}
   * @memberof V1beta1DataImportCron
   */
  spec: V1beta1DataImportCronSpec;
  /**
   *
   * @type {V1beta1DataImportCronStatus}
   * @memberof V1beta1DataImportCron
   */
  status?: V1beta1DataImportCronStatus;
}
