/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt Containerized Data Importer API
 * Containerized Data Importer for KubeVirt.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  V1LabelSelector,
  V1TypedLocalObjectReference,
  V1TypedObjectReference,
  V1VolumeResourceRequirements,
} from './';

/**
 * PersistentVolumeClaimSpec describes the common attributes of storage devices and allows a Source for provider-specific attributes
 * @export
 * @interface V1PersistentVolumeClaimSpec
 */
export interface V1PersistentVolumeClaimSpec {
  /**
   * accessModes contains the desired access modes the volume should have. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1
   * @type {Array<string>}
   * @memberof V1PersistentVolumeClaimSpec
   */
  accessModes?: Array<V1PersistentVolumeClaimSpecAccessModesEnum>;
  /**
   *
   * @type {V1TypedLocalObjectReference}
   * @memberof V1PersistentVolumeClaimSpec
   */
  dataSource?: V1TypedLocalObjectReference;
  /**
   *
   * @type {V1TypedObjectReference}
   * @memberof V1PersistentVolumeClaimSpec
   */
  dataSourceRef?: V1TypedObjectReference;
  /**
   *
   * @type {V1VolumeResourceRequirements}
   * @memberof V1PersistentVolumeClaimSpec
   */
  resources?: V1VolumeResourceRequirements;
  /**
   *
   * @type {V1LabelSelector}
   * @memberof V1PersistentVolumeClaimSpec
   */
  selector?: V1LabelSelector;
  /**
   * storageClassName is the name of the StorageClass required by the claim. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#class-1
   * @type {string}
   * @memberof V1PersistentVolumeClaimSpec
   */
  storageClassName?: string;
  /**
   * volumeAttributesClassName may be used to set the VolumeAttributesClass used by this claim. If specified, the CSI driver will create or update the volume with the attributes defined in the corresponding VolumeAttributesClass. This has a different purpose than storageClassName, it can be changed after the claim is created. An empty string value means that no VolumeAttributesClass will be applied to the claim but it's not allowed to reset this field to empty string once it is set. If unspecified and the PersistentVolumeClaim is unbound, the default VolumeAttributesClass will be set by the persistentvolume controller if it exists. If the resource referred to by volumeAttributesClass does not exist, this PersistentVolumeClaim will be set to a Pending state, as reflected by the modifyVolumeStatus field, until such as a resource exists. More info: https://kubernetes.io/docs/concepts/storage/volume-attributes-classes/ (Beta) Using this field requires the VolumeAttributesClass feature gate to be enabled (off by default).
   * @type {string}
   * @memberof V1PersistentVolumeClaimSpec
   */
  volumeAttributesClassName?: string;
  /**
   * volumeMode defines what type of volume is required by the claim. Value of Filesystem is implied when not included in claim spec.
   *
   * Possible enum values:
   *  - `"Block"` means the volume will not be formatted with a filesystem and will remain a raw block device.
   *  - `"Filesystem"` means the volume will be or is formatted with a filesystem.
   *  - `"FromStorageProfile"` means the volume mode will be auto selected by CDI according to a matching StorageProfile
   * @type {string}
   * @memberof V1PersistentVolumeClaimSpec
   */
  volumeMode?: V1PersistentVolumeClaimSpecVolumeModeEnum;
  /**
   * volumeName is the binding reference to the PersistentVolume backing this claim.
   * @type {string}
   * @memberof V1PersistentVolumeClaimSpec
   */
  volumeName?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum V1PersistentVolumeClaimSpecAccessModesEnum {
  ReadOnlyMany = 'ReadOnlyMany',
  ReadWriteMany = 'ReadWriteMany',
  ReadWriteOnce = 'ReadWriteOnce',
  ReadWriteOncePod = 'ReadWriteOncePod',
}
/**
 * @export
 * @enum {string}
 */
export enum V1PersistentVolumeClaimSpecVolumeModeEnum {
  Block = 'Block',
  Filesystem = 'Filesystem',
  FromStorageProfile = 'FromStorageProfile',
}
