/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1FeatureAPIC } from './V1FeatureAPIC';
import { V1FeatureHyperv } from './V1FeatureHyperv';
import { V1FeatureKVM } from './V1FeatureKVM';
import { V1FeatureState } from './V1FeatureState';

export class V1Features {
    'acpi'?: V1FeatureState;
    'apic'?: V1FeatureAPIC;
    'hyperv'?: V1FeatureHyperv;
    'kvm'?: V1FeatureKVM;
    'pvspinlock'?: V1FeatureState;
    'smm'?: V1FeatureState;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "acpi",
            "baseName": "acpi",
            "type": "V1FeatureState",
            "format": ""
        },
        {
            "name": "apic",
            "baseName": "apic",
            "type": "V1FeatureAPIC",
            "format": ""
        },
        {
            "name": "hyperv",
            "baseName": "hyperv",
            "type": "V1FeatureHyperv",
            "format": ""
        },
        {
            "name": "kvm",
            "baseName": "kvm",
            "type": "V1FeatureKVM",
            "format": ""
        },
        {
            "name": "pvspinlock",
            "baseName": "pvspinlock",
            "type": "V1FeatureState",
            "format": ""
        },
        {
            "name": "smm",
            "baseName": "smm",
            "type": "V1FeatureState",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1Features.attributeTypeMap;
    }

    public constructor() {
    }
}

