/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* GenerationStatus keeps track of the generation for a given resource so that decisions about forced updates can be made.
*/
export class V1GenerationStatus {
    /**
    * group is the group of the thing you're tracking
    */
    'group': string;
    /**
    * hash is an optional field set for resources without generation that are content sensitive like secrets and configmaps
    */
    'hash'?: string;
    /**
    * lastGeneration is the last generation of the workload controller involved
    */
    'lastGeneration': number;
    /**
    * name is the name of the thing you're tracking
    */
    'name': string;
    /**
    * namespace is where the thing you're tracking is
    */
    'namespace'?: string;
    /**
    * resource is the resource type of the thing you're tracking
    */
    'resource': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "group",
            "baseName": "group",
            "type": "string",
            "format": ""
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastGeneration",
            "baseName": "lastGeneration",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "namespace",
            "baseName": "namespace",
            "type": "string",
            "format": ""
        },
        {
            "name": "resource",
            "baseName": "resource",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1GenerationStatus.attributeTypeMap;
    }

    public constructor() {
    }
}

