/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { K8sIoApiCoreV1Affinity } from './K8sIoApiCoreV1Affinity';
import { K8sIoApiCoreV1PodDNSConfig } from './K8sIoApiCoreV1PodDNSConfig';
import { K8sIoApiCoreV1Toleration } from './K8sIoApiCoreV1Toleration';
import { V1AccessCredential } from './V1AccessCredential';
import { V1DomainSpec } from './V1DomainSpec';
import { V1Network } from './V1Network';
import { V1Probe } from './V1Probe';
import { V1Volume } from './V1Volume';

/**
* VirtualMachineInstanceSpec is a description of a VirtualMachineInstance.
*/
export class V1VirtualMachineInstanceSpec {
    /**
    * Specifies a set of public keys to inject into the vm guest
    */
    'accessCredentials'?: Array<V1AccessCredential>;
    'affinity'?: K8sIoApiCoreV1Affinity;
    'dnsConfig'?: K8sIoApiCoreV1PodDNSConfig;
    /**
    * Set DNS policy for the pod. Defaults to \"ClusterFirst\". Valid values are 'ClusterFirstWithHostNet', 'ClusterFirst', 'Default' or 'None'. DNS parameters given in DNSConfig will be merged with the policy selected with DNSPolicy. To have DNS options set along with hostNetwork, you have to specify DNS policy explicitly to 'ClusterFirstWithHostNet'.
    */
    'dnsPolicy'?: string;
    'domain': V1DomainSpec;
    /**
    * EvictionStrategy can be set to \"LiveMigrate\" if the VirtualMachineInstance should be migrated instead of shut-off in case of a node drain.
    */
    'evictionStrategy'?: string;
    /**
    * Specifies the hostname of the vmi If not specified, the hostname will be set to the name of the vmi, if dhcp or cloud-init is configured properly.
    */
    'hostname'?: string;
    'livenessProbe'?: V1Probe;
    /**
    * List of networks that can be attached to a vm's virtual interface.
    */
    'networks'?: Array<V1Network>;
    /**
    * NodeSelector is a selector which must be true for the vmi to fit on a node. Selector which must match a node's labels for the vmi to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
    */
    'nodeSelector'?: { [key: string]: string; };
    /**
    * If specified, indicates the pod's priority. If not specified, the pod priority will be default or zero if there is no default.
    */
    'priorityClassName'?: string;
    'readinessProbe'?: V1Probe;
    /**
    * If specified, the VMI will be dispatched by specified scheduler. If not specified, the VMI will be dispatched by default scheduler.
    */
    'schedulerName'?: string;
    /**
    * StartStrategy can be set to \"Paused\" if Virtual Machine should be started in paused state.
    */
    'startStrategy'?: string;
    /**
    * If specified, the fully qualified vmi hostname will be \"<hostname>.<subdomain>.<pod namespace>.svc.<cluster domain>\". If not specified, the vmi will not have a domainname at all. The DNS entry will resolve to the vmi, no matter if the vmi itself can pick up a hostname.
    */
    'subdomain'?: string;
    /**
    * Grace period observed after signalling a VirtualMachineInstance to stop after which the VirtualMachineInstance is force terminated.
    */
    'terminationGracePeriodSeconds'?: number;
    /**
    * If toleration is specified, obey all the toleration rules.
    */
    'tolerations'?: Array<K8sIoApiCoreV1Toleration>;
    /**
    * List of volumes that can be mounted by disks belonging to the vmi.
    */
    'volumes'?: Array<V1Volume>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accessCredentials",
            "baseName": "accessCredentials",
            "type": "Array<V1AccessCredential>",
            "format": ""
        },
        {
            "name": "affinity",
            "baseName": "affinity",
            "type": "K8sIoApiCoreV1Affinity",
            "format": ""
        },
        {
            "name": "dnsConfig",
            "baseName": "dnsConfig",
            "type": "K8sIoApiCoreV1PodDNSConfig",
            "format": ""
        },
        {
            "name": "dnsPolicy",
            "baseName": "dnsPolicy",
            "type": "string",
            "format": ""
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "V1DomainSpec",
            "format": ""
        },
        {
            "name": "evictionStrategy",
            "baseName": "evictionStrategy",
            "type": "string",
            "format": ""
        },
        {
            "name": "hostname",
            "baseName": "hostname",
            "type": "string",
            "format": ""
        },
        {
            "name": "livenessProbe",
            "baseName": "livenessProbe",
            "type": "V1Probe",
            "format": ""
        },
        {
            "name": "networks",
            "baseName": "networks",
            "type": "Array<V1Network>",
            "format": ""
        },
        {
            "name": "nodeSelector",
            "baseName": "nodeSelector",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "priorityClassName",
            "baseName": "priorityClassName",
            "type": "string",
            "format": ""
        },
        {
            "name": "readinessProbe",
            "baseName": "readinessProbe",
            "type": "V1Probe",
            "format": ""
        },
        {
            "name": "schedulerName",
            "baseName": "schedulerName",
            "type": "string",
            "format": ""
        },
        {
            "name": "startStrategy",
            "baseName": "startStrategy",
            "type": "string",
            "format": ""
        },
        {
            "name": "subdomain",
            "baseName": "subdomain",
            "type": "string",
            "format": ""
        },
        {
            "name": "terminationGracePeriodSeconds",
            "baseName": "terminationGracePeriodSeconds",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "tolerations",
            "baseName": "tolerations",
            "type": "Array<K8sIoApiCoreV1Toleration>",
            "format": ""
        },
        {
            "name": "volumes",
            "baseName": "volumes",
            "type": "Array<V1Volume>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1VirtualMachineInstanceSpec.attributeTypeMap;
    }

    public constructor() {
    }
}

