/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { K8sIoApimachineryPkgApisMetaV1LabelSelector } from './K8sIoApimachineryPkgApisMetaV1LabelSelector';
import { V1DomainSpec } from './V1DomainSpec';

export class V1VirtualMachineInstancePresetSpec {
    'domain'?: V1DomainSpec;
    'selector': K8sIoApimachineryPkgApisMetaV1LabelSelector;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "domain",
            "baseName": "domain",
            "type": "V1DomainSpec",
            "format": ""
        },
        {
            "name": "selector",
            "baseName": "selector",
            "type": "K8sIoApimachineryPkgApisMetaV1LabelSelector",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1VirtualMachineInstancePresetSpec.attributeTypeMap;
    }

    public constructor() {
    }
}

