/**
 * 
 * 
 *
 * The version of the OpenAPI document: 
 * Contact Email: 
 * License: 
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { V1beta1NMStateSpecInfraAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelectorMatchExpressions } from './V1beta1NMStateSpecInfraAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelectorMatchExpressions';

/**
 * A label query over a set of resources, in this case pods.
If it&#39;s null, this PodAffinityTerm matches with no Pods.
 *
 * @export
 */
export interface V1beta1NMStateSpecInfraAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelector {
  /** matchExpressions
   * A label selector requirement is a selector that contains values, a key, and an operator that
relates the key and values.
   *
   * @required {false}
   */
  matchExpressions?: V1beta1NMStateSpecInfraAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelectorMatchExpressions[];
  /** matchLabels
   * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
map is equivalent to an element of matchExpressions, whose key field is "key", the
operator is "In", and the values array contains only "value". The requirements are ANDed.
   *
   * @required {false}
   * @originalType {V1beta1NMStateSpecInfraAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelectorMatchLabels}
   */
  matchLabels?: {[key: string]: string};
}
