/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1NMStateSpecAffinityNodeAffinity } from './V1NMStateSpecAffinityNodeAffinity';
import {
    V1NMStateSpecAffinityNodeAffinityFromJSON,
    V1NMStateSpecAffinityNodeAffinityFromJSONTyped,
    V1NMStateSpecAffinityNodeAffinityToJSON,
} from './V1NMStateSpecAffinityNodeAffinity';
import type { V1NMStateSpecAffinityPodAffinity } from './V1NMStateSpecAffinityPodAffinity';
import {
    V1NMStateSpecAffinityPodAffinityFromJSON,
    V1NMStateSpecAffinityPodAffinityFromJSONTyped,
    V1NMStateSpecAffinityPodAffinityToJSON,
} from './V1NMStateSpecAffinityPodAffinity';
import type { V1NMStateSpecAffinityPodAntiAffinity } from './V1NMStateSpecAffinityPodAntiAffinity';
import {
    V1NMStateSpecAffinityPodAntiAffinityFromJSON,
    V1NMStateSpecAffinityPodAntiAffinityFromJSONTyped,
    V1NMStateSpecAffinityPodAntiAffinityToJSON,
} from './V1NMStateSpecAffinityPodAntiAffinity';

/**
 * InfraAffinity is an optional affinity selector that will be added to webhook, metrics & console-plugin Deployment manifests.
 * @export
 * @interface V1NMStateSpecInfraAffinity
 */
export interface V1NMStateSpecInfraAffinity {
    /**
     * 
     * @type {V1NMStateSpecAffinityNodeAffinity}
     * @memberof V1NMStateSpecInfraAffinity
     */
    nodeAffinity?: V1NMStateSpecAffinityNodeAffinity;
    /**
     * 
     * @type {V1NMStateSpecAffinityPodAffinity}
     * @memberof V1NMStateSpecInfraAffinity
     */
    podAffinity?: V1NMStateSpecAffinityPodAffinity;
    /**
     * 
     * @type {V1NMStateSpecAffinityPodAntiAffinity}
     * @memberof V1NMStateSpecInfraAffinity
     */
    podAntiAffinity?: V1NMStateSpecAffinityPodAntiAffinity;
}

/**
 * Check if a given object implements the V1NMStateSpecInfraAffinity interface.
 */
export function instanceOfV1NMStateSpecInfraAffinity(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1NMStateSpecInfraAffinityFromJSON(json: any): V1NMStateSpecInfraAffinity {
    return V1NMStateSpecInfraAffinityFromJSONTyped(json, false);
}

export function V1NMStateSpecInfraAffinityFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1NMStateSpecInfraAffinity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nodeAffinity': !exists(json, 'nodeAffinity') ? undefined : V1NMStateSpecAffinityNodeAffinityFromJSON(json['nodeAffinity']),
        'podAffinity': !exists(json, 'podAffinity') ? undefined : V1NMStateSpecAffinityPodAffinityFromJSON(json['podAffinity']),
        'podAntiAffinity': !exists(json, 'podAntiAffinity') ? undefined : V1NMStateSpecAffinityPodAntiAffinityFromJSON(json['podAntiAffinity']),
    };
}

export function V1NMStateSpecInfraAffinityToJSON(value?: V1NMStateSpecInfraAffinity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nodeAffinity': V1NMStateSpecAffinityNodeAffinityToJSON(value.nodeAffinity),
        'podAffinity': V1NMStateSpecAffinityPodAffinityToJSON(value.podAffinity),
        'podAntiAffinity': V1NMStateSpecAffinityPodAntiAffinityToJSON(value.podAntiAffinity),
    };
}

