/* tslint:disable */
/* eslint-disable */
/**
 *
 *
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  V1NMStateSpecAffinityNodeAffinityPreferenceMatchExpressions,
  V1NMStateSpecAffinityNodeAffinityPreferenceMatchExpressionsFromJSON,
  V1NMStateSpecAffinityNodeAffinityPreferenceMatchExpressionsFromJSONTyped,
  V1NMStateSpecAffinityNodeAffinityPreferenceMatchExpressionsToJSON,
} from './';

/**
 * A null or empty node selector term matches no objects. The requirements of them are ANDed. The TopologySelectorTerm type implements a subset of the NodeSelectorTerm.
 * @export
 * @interface V1NMStateSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTerms
 */
export interface V1NMStateSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTerms {
  /**
   * A list of node selector requirements by node's labels.
   * @type {Array<V1NMStateSpecAffinityNodeAffinityPreferenceMatchExpressions>}
   * @memberof V1NMStateSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTerms
   */
  matchExpressions?: Array<V1NMStateSpecAffinityNodeAffinityPreferenceMatchExpressions>;
  /**
   * A list of node selector requirements by node's fields.
   * @type {Array<V1NMStateSpecAffinityNodeAffinityPreferenceMatchExpressions>}
   * @memberof V1NMStateSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTerms
   */
  matchFields?: Array<V1NMStateSpecAffinityNodeAffinityPreferenceMatchExpressions>;
}

export function V1NMStateSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsFromJSON(
  json: any,
): V1NMStateSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTerms {
  return V1NMStateSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsFromJSONTyped(
    json,
    false,
  );
}

export function V1NMStateSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsFromJSONTyped(
  json: any,
  _ignoreDiscriminator: boolean,
): V1NMStateSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTerms {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    matchExpressions: !exists(json, 'matchExpressions')
      ? undefined
      : (json['matchExpressions'] as Array<any>).map(
          V1NMStateSpecAffinityNodeAffinityPreferenceMatchExpressionsFromJSON,
        ),
    matchFields: !exists(json, 'matchFields')
      ? undefined
      : (json['matchFields'] as Array<any>).map(
          V1NMStateSpecAffinityNodeAffinityPreferenceMatchExpressionsFromJSON,
        ),
  };
}

export function V1NMStateSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsToJSON(
  value?: V1NMStateSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTerms | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    matchExpressions:
      value.matchExpressions === undefined
        ? undefined
        : (value.matchExpressions as Array<any>).map(
            V1NMStateSpecAffinityNodeAffinityPreferenceMatchExpressionsToJSON,
          ),
    matchFields:
      value.matchFields === undefined
        ? undefined
        : (value.matchFields as Array<any>).map(
            V1NMStateSpecAffinityNodeAffinityPreferenceMatchExpressionsToJSON,
          ),
  };
}
