/* tslint:disable */
/* eslint-disable */
/**
 *
 *
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * SelfSignConfiguration defines self signed certificate configuration
 * @export
 * @interface V1NMStateSpecSelfSignConfiguration
 */
export interface V1NMStateSpecSelfSignConfiguration {
  /**
   * CAOverlapInterval defines the duration where expired CA certificate can overlap with new one, in order to allow fluent CA rotation transitioning
   * @type {string}
   * @memberof V1NMStateSpecSelfSignConfiguration
   */
  caOverlapInterval?: string;
  /**
   * CARotateInterval defines duration for CA expiration
   * @type {string}
   * @memberof V1NMStateSpecSelfSignConfiguration
   */
  caRotateInterval?: string;
  /**
   * CertOverlapInterval defines the duration where expired service certificate can overlap with new one, in order to allow fluent service rotation transitioning
   * @type {string}
   * @memberof V1NMStateSpecSelfSignConfiguration
   */
  certOverlapInterval?: string;
  /**
   * CertRotateInterval defines duration for of service certificate expiration
   * @type {string}
   * @memberof V1NMStateSpecSelfSignConfiguration
   */
  certRotateInterval?: string;
}

export function V1NMStateSpecSelfSignConfigurationFromJSON(
  json: any,
): V1NMStateSpecSelfSignConfiguration {
  return V1NMStateSpecSelfSignConfigurationFromJSONTyped(json, false);
}

export function V1NMStateSpecSelfSignConfigurationFromJSONTyped(
  json: any,
  _ignoreDiscriminator: boolean,
): V1NMStateSpecSelfSignConfiguration {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    caOverlapInterval: !exists(json, 'caOverlapInterval') ? undefined : json['caOverlapInterval'],
    caRotateInterval: !exists(json, 'caRotateInterval') ? undefined : json['caRotateInterval'],
    certOverlapInterval: !exists(json, 'certOverlapInterval')
      ? undefined
      : json['certOverlapInterval'],
    certRotateInterval: !exists(json, 'certRotateInterval')
      ? undefined
      : json['certRotateInterval'],
  };
}

export function V1NMStateSpecSelfSignConfigurationToJSON(
  value?: V1NMStateSpecSelfSignConfiguration | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    caOverlapInterval: value.caOverlapInterval,
    caRotateInterval: value.caRotateInterval,
    certOverlapInterval: value.certOverlapInterval,
    certRotateInterval: value.certRotateInterval,
  };
}
