/* tslint:disable */
/* eslint-disable */
/**
 *
 *
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  V1NMStateSpecAffinityNodeAffinityPreference,
  V1NMStateSpecAffinityNodeAffinityPreferenceFromJSON,
  V1NMStateSpecAffinityNodeAffinityPreferenceFromJSONTyped,
  V1NMStateSpecAffinityNodeAffinityPreferenceToJSON,
} from './';

/**
 * An empty preferred scheduling term matches all objects with implicit weight 0 (i.e. it's a no-op). A null preferred scheduling term matches no objects (i.e. is also a no-op).
 * @export
 * @interface V1NMStateSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution
 */
export interface V1NMStateSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution {
  /**
   *
   * @type {V1NMStateSpecAffinityNodeAffinityPreference}
   * @memberof V1NMStateSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution
   */
  preference: V1NMStateSpecAffinityNodeAffinityPreference;
  /**
   * Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100.
   * @type {number}
   * @memberof V1NMStateSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution
   */
  weight: number;
}

export function V1NMStateSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionFromJSON(
  json: any,
): V1NMStateSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution {
  return V1NMStateSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionFromJSONTyped(
    json,
    false,
  );
}

export function V1NMStateSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionFromJSONTyped(
  json: any,
  _ignoreDiscriminator: boolean,
): V1NMStateSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    preference: V1NMStateSpecAffinityNodeAffinityPreferenceFromJSON(json['preference']),
    weight: json['weight'],
  };
}

export function V1NMStateSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionToJSON(
  value?: V1NMStateSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    preference: V1NMStateSpecAffinityNodeAffinityPreferenceToJSON(value.preference),
    weight: value.weight,
  };
}
