/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { V1NMStateSpecAffinityNodeAffinity } from './V1NMStateSpecAffinityNodeAffinity';
import type { V1NMStateSpecAffinityPodAffinity } from './V1NMStateSpecAffinityPodAffinity';
import type { V1NMStateSpecAffinityPodAntiAffinity } from './V1NMStateSpecAffinityPodAntiAffinity';

/**
 * Affinity is an optional affinity selector that will be added to handler DaemonSet manifest.
 * @export
 * @interface V1NMStateSpecAffinity
 */
export interface V1NMStateSpecAffinity {
  /**
   *
   * @type {V1NMStateSpecAffinityNodeAffinity}
   * @memberof V1NMStateSpecAffinity
   */
  nodeAffinity?: V1NMStateSpecAffinityNodeAffinity;
  /**
   *
   * @type {V1NMStateSpecAffinityPodAffinity}
   * @memberof V1NMStateSpecAffinity
   */
  podAffinity?: V1NMStateSpecAffinityPodAffinity;
  /**
   *
   * @type {V1NMStateSpecAffinityPodAntiAffinity}
   * @memberof V1NMStateSpecAffinity
   */
  podAntiAffinity?: V1NMStateSpecAffinityPodAntiAffinity;
}
