/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * SelfSignConfiguration defines self signed certificate configuration
 * @export
 * @interface V1NMStateSpecSelfSignConfiguration
 */
export interface V1NMStateSpecSelfSignConfiguration {
  /**
   * CAOverlapInterval defines the duration where expired CA certificate
   * can overlap with new one, in order to allow fluent CA rotation transitioning
   * @type {any}
   * @memberof V1NMStateSpecSelfSignConfiguration
   */
  caOverlapInterval?: any | null;
  /**
   * CARotateInterval defines duration for CA expiration
   * @type {any}
   * @memberof V1NMStateSpecSelfSignConfiguration
   */
  caRotateInterval?: any | null;
  /**
   * CertOverlapInterval defines the duration where expired service certificate
   * can overlap with new one, in order to allow fluent service rotation transitioning
   * @type {any}
   * @memberof V1NMStateSpecSelfSignConfiguration
   */
  certOverlapInterval?: any | null;
  /**
   * CertRotateInterval defines duration for of service certificate expiration
   * @type {any}
   * @memberof V1NMStateSpecSelfSignConfiguration
   */
  certRotateInterval?: any | null;
}
