/* tslint:disable */
/* eslint-disable */
/**
 *
 *
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface V1NodeNetworkConfigurationPolicyStatusConditions
 */
export interface V1NodeNetworkConfigurationPolicyStatusConditions {
  /**
   *
   * @type {string}
   * @memberof V1NodeNetworkConfigurationPolicyStatusConditions
   */
  lastHearbeatTime?: string;
  /**
   *
   * @type {string}
   * @memberof V1NodeNetworkConfigurationPolicyStatusConditions
   */
  lastTransitionTime?: string;
  /**
   *
   * @type {string}
   * @memberof V1NodeNetworkConfigurationPolicyStatusConditions
   */
  message?: string;
  /**
   *
   * @type {string}
   * @memberof V1NodeNetworkConfigurationPolicyStatusConditions
   */
  messageEncoded?: string;
  /**
   *
   * @type {string}
   * @memberof V1NodeNetworkConfigurationPolicyStatusConditions
   */
  reason?: string;
  /**
   *
   * @type {string}
   * @memberof V1NodeNetworkConfigurationPolicyStatusConditions
   */
  status: string;
  /**
   *
   * @type {string}
   * @memberof V1NodeNetworkConfigurationPolicyStatusConditions
   */
  type: string;
}

export function V1NodeNetworkConfigurationPolicyStatusConditionsFromJSON(
  json: any,
): V1NodeNetworkConfigurationPolicyStatusConditions {
  return V1NodeNetworkConfigurationPolicyStatusConditionsFromJSONTyped(json, false);
}

export function V1NodeNetworkConfigurationPolicyStatusConditionsFromJSONTyped(
  json: any,
  _ignoreDiscriminator: boolean,
): V1NodeNetworkConfigurationPolicyStatusConditions {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    lastHearbeatTime: !exists(json, 'lastHearbeatTime') ? undefined : json['lastHearbeatTime'],
    lastTransitionTime: !exists(json, 'lastTransitionTime')
      ? undefined
      : json['lastTransitionTime'],
    message: !exists(json, 'message') ? undefined : json['message'],
    messageEncoded: !exists(json, 'messageEncoded') ? undefined : json['messageEncoded'],
    reason: !exists(json, 'reason') ? undefined : json['reason'],
    status: json['status'],
    type: json['type'],
  };
}

export function V1NodeNetworkConfigurationPolicyStatusConditionsToJSON(
  value?: V1NodeNetworkConfigurationPolicyStatusConditions | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    lastHearbeatTime: value.lastHearbeatTime === undefined ? undefined : value.lastHearbeatTime,
    lastTransitionTime:
      value.lastTransitionTime === undefined ? undefined : value.lastTransitionTime,
    message: value.message,
    messageEncoded: value.messageEncoded,
    reason: value.reason,
    status: value.status,
    type: value.type,
  };
}
