/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * NodeNetworkConfigurationPolicyStatus defines the observed state of NodeNetworkConfigurationPolicy
 * @export
 * @interface V1NodeNetworkConfigurationPolicyStatus
 */
export interface V1NodeNetworkConfigurationPolicyStatus {
    /**
     * 
     * @type {any}
     * @memberof V1NodeNetworkConfigurationPolicyStatus
     */
    conditions?: any | null;
    /**
     * LastUnavailableNodeCountUpdate is time of the last UnavailableNodeCount update
     * @type {any}
     * @memberof V1NodeNetworkConfigurationPolicyStatus
     */
    lastUnavailableNodeCountUpdate?: any | null;
    /**
     * UnavailableNodeCount represents the total number of potentially unavailable nodes that are
     * processing a NodeNetworkConfigurationPolicy
     * @type {any}
     * @memberof V1NodeNetworkConfigurationPolicyStatus
     */
    unavailableNodeCount?: any | null;
}

/**
 * Check if a given object implements the V1NodeNetworkConfigurationPolicyStatus interface.
 */
export function instanceOfV1NodeNetworkConfigurationPolicyStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1NodeNetworkConfigurationPolicyStatusFromJSON(json: any): V1NodeNetworkConfigurationPolicyStatus {
    return V1NodeNetworkConfigurationPolicyStatusFromJSONTyped(json, false);
}

export function V1NodeNetworkConfigurationPolicyStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1NodeNetworkConfigurationPolicyStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'conditions': !exists(json, 'conditions') ? undefined : json['conditions'],
        'lastUnavailableNodeCountUpdate': !exists(json, 'lastUnavailableNodeCountUpdate') ? undefined : json['lastUnavailableNodeCountUpdate'],
        'unavailableNodeCount': !exists(json, 'unavailableNodeCount') ? undefined : json['unavailableNodeCount'],
    };
}

export function V1NodeNetworkConfigurationPolicyStatusToJSON(value?: V1NodeNetworkConfigurationPolicyStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'conditions': value.conditions,
        'lastUnavailableNodeCountUpdate': value.lastUnavailableNodeCountUpdate,
        'unavailableNodeCount': value.unavailableNodeCount,
    };
}

