/**
 *
 *
 *
 * The version of the OpenAPI document:
 * Contact Email:
 * License:
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

/**
 * VirtualMachineReference holds a reference to a VirtualMachine.kubevirt.io
 *
 * @export
 */
export interface V1alpha1VirtualMachineTemplateRequestSpecVirtualMachineRef {
  /** name
   * Name is the name of the VirtualMachine.
   *
   * @required {true}
   */
  name: string;
  /** namespace
   * Namespace is the namespace of the VirtualMachine.
   *
   * @required {true}
   */
  namespace: string;
}
