/**
 *
 *
 *
 * The version of the OpenAPI document:
 * Contact Email:
 * License:
 *
 * NOTE: This file is auto generated by crdtotypes (https://github.com/yaacov/crdtoapi/).
 * https://github.com/yaacov/crdtoapi/README.crdtotypes
 */

import { V1beta1VirtualMachineTemplateRequestSpecVirtualMachineRef } from './V1beta1VirtualMachineTemplateRequestSpecVirtualMachineRef';

/**
 * Spec defines the desired state of the template requests
 *
 * @export
 */
export interface V1beta1VirtualMachineTemplateRequestSpec {
  /** templateLabels
   * TemplateLabels holds optional labels to apply to the created VirtualMachineTemplate.
Labels with the "template.kubevirt.io/" prefix are reserved for system use and are not allowed.
   *
   * @required {false}
   * @originalType {V1beta1VirtualMachineTemplateRequestSpecTemplateLabels}
   */
  templateLabels?: { [key: string]: string };
  /** templateName
   * TemplateName holds the optional name for the new VirtualMachineTemplate.
If not specified the template will have the same name as the VirtualMachineTemplateRequest.
   *
   * @required {false}
   */
  templateName?: string;
  /** ttlSecondsAfterFinished
   * TTLSecondsAfterFinished limits the lifetime of a VirtualMachineTemplateRequest
that has finished execution. Failed VirtualMachineTemplateRequests are never
cleaned up by the TTL controller, so they remain available for debugging. If
this field is unset, the VirtualMachineTemplateRequest is not automatically
deleted and must be removed manually or through the owner reference cleanup
described below. If this field is set to zero, the VirtualMachineTemplateRequest
becomes eligible to be deleted immediately after it finishes.
   *
   * @required {false}
   * @format {int32}
   * @originalType {integer}
   */
  ttlSecondsAfterFinished?: number;
  /** virtualMachineRef
   * VirtualMachineReference holds a reference to a VirtualMachine.kubevirt.io
   *
   * @required {true}
   */
  virtualMachineRef: V1beta1VirtualMachineTemplateRequestSpecVirtualMachineRef;
}
