/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinition,
  IoK8sApimachineryPkgApisMetaV1ListMeta,
} from './';

/**
 * CustomResourceDefinitionList is a list of CustomResourceDefinition objects.
 * @export
 * @interface IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionList
 */
export interface IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionList {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   * @type {string}
   * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionList
   */
  apiVersion?: string;
  /**
   * items list individual CustomResourceDefinition objects
   * @type {Array<IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinition>}
   * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionList
   */
  items: Array<IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinition>;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   * @type {string}
   * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionList
   */
  kind?: string;
  /**
   *
   * @type {IoK8sApimachineryPkgApisMetaV1ListMeta}
   * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionList
   */
  metadata?: IoK8sApimachineryPkgApisMetaV1ListMeta;
}
