/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * EventSource contains information for an event.
 * @export
 * @interface IoK8sApiCoreV1EventSource
 */
export interface IoK8sApiCoreV1EventSource {
  /**
   * Component from which the event is generated.
   * @type {string}
   * @memberof IoK8sApiCoreV1EventSource
   */
  component?: string;
  /**
   * Node name on which the event is generated.
   * @type {string}
   * @memberof IoK8sApiCoreV1EventSource
   */
  host?: string;
}
