/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * NodeCondition contains condition information for a node.
 * @export
 * @interface IoK8sApiCoreV1NodeCondition
 */
export interface IoK8sApiCoreV1NodeCondition {
  /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   * @type {string}
   * @memberof IoK8sApiCoreV1NodeCondition
   */
  lastHeartbeatTime?: string;
  /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   * @type {string}
   * @memberof IoK8sApiCoreV1NodeCondition
   */
  lastTransitionTime?: string;
  /**
   * Human readable message indicating details about last transition.
   * @type {string}
   * @memberof IoK8sApiCoreV1NodeCondition
   */
  message?: string;
  /**
   * (brief) reason for the condition's last transition.
   * @type {string}
   * @memberof IoK8sApiCoreV1NodeCondition
   */
  reason?: string;
  /**
   * Status of the condition, one of True, False, Unknown.
   * @type {string}
   * @memberof IoK8sApiCoreV1NodeCondition
   */
  status: string;
  /**
   * Type of node condition.
   * @type {string}
   * @memberof IoK8sApiCoreV1NodeCondition
   */
  type: string;
}
