/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * LeaseCandidateSpec is a specification of a Lease.
 * @export
 * @interface IoK8sApiCoordinationV1alpha2LeaseCandidateSpec
 */
export interface IoK8sApiCoordinationV1alpha2LeaseCandidateSpec {
  /**
   * BinaryVersion is the binary version. It must be in a semver format without leading `v`. This field is required.
   * @type {string}
   * @memberof IoK8sApiCoordinationV1alpha2LeaseCandidateSpec
   */
  binaryVersion: string;
  /**
   * EmulationVersion is the emulation version. It must be in a semver format without leading `v`. EmulationVersion must be less than or equal to BinaryVersion. This field is required when strategy is "OldestEmulationVersion"
   * @type {string}
   * @memberof IoK8sApiCoordinationV1alpha2LeaseCandidateSpec
   */
  emulationVersion?: string;
  /**
   * LeaseName is the name of the lease for which this candidate is contending. This field is immutable.
   * @type {string}
   * @memberof IoK8sApiCoordinationV1alpha2LeaseCandidateSpec
   */
  leaseName: string;
  /**
   * MicroTime is version of Time with microsecond level precision.
   * @type {string}
   * @memberof IoK8sApiCoordinationV1alpha2LeaseCandidateSpec
   */
  pingTime?: string;
  /**
   * MicroTime is version of Time with microsecond level precision.
   * @type {string}
   * @memberof IoK8sApiCoordinationV1alpha2LeaseCandidateSpec
   */
  renewTime?: string;
  /**
   * Strategy is the strategy that coordinated leader election will use for picking the leader. If multiple candidates for the same Lease return different strategies, the strategy provided by the candidate with the latest BinaryVersion will be used. If there is still conflict, this is a user error and coordinated leader election will not operate the Lease until resolved.
   * @type {string}
   * @memberof IoK8sApiCoordinationV1alpha2LeaseCandidateSpec
   */
  strategy: string;
}
