/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
  IoK8sApiResourceV1beta1OpaqueDeviceConfiguration,
  IoK8sApiResourceV1beta1OpaqueDeviceConfigurationFromJSON,
  IoK8sApiResourceV1beta1OpaqueDeviceConfigurationToJSON,
} from './';

/**
 * DeviceClassConfiguration is used in DeviceClass.
 * @export
 * @interface IoK8sApiResourceV1beta1DeviceClassConfiguration
 */
export interface IoK8sApiResourceV1beta1DeviceClassConfiguration {
  /**
   *
   * @type {IoK8sApiResourceV1beta1OpaqueDeviceConfiguration}
   * @memberof IoK8sApiResourceV1beta1DeviceClassConfiguration
   */
  opaque?: IoK8sApiResourceV1beta1OpaqueDeviceConfiguration;
}

export function IoK8sApiResourceV1beta1DeviceClassConfigurationFromJSON(
  json: any,
): IoK8sApiResourceV1beta1DeviceClassConfiguration {
  return IoK8sApiResourceV1beta1DeviceClassConfigurationFromJSONTyped(json, false);
}

export function IoK8sApiResourceV1beta1DeviceClassConfigurationFromJSONTyped(
  json: any,
  _ignoreDiscriminator: boolean,
): IoK8sApiResourceV1beta1DeviceClassConfiguration {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    opaque: !exists(json, 'opaque')
      ? undefined
      : IoK8sApiResourceV1beta1OpaqueDeviceConfigurationFromJSON(json['opaque']),
  };
}

export function IoK8sApiResourceV1beta1DeviceClassConfigurationToJSON(
  value?: IoK8sApiResourceV1beta1DeviceClassConfiguration | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    opaque: IoK8sApiResourceV1beta1OpaqueDeviceConfigurationToJSON(value.opaque),
  };
}
