/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The node this Taint is attached to has the "effect" on any pod that does not tolerate the Taint.
 * @export
 * @interface IoK8sApiCoreV1Taint
 */
export interface IoK8sApiCoreV1Taint {
  /**
   * Required. The effect of the taint on pods that do not tolerate the taint. Valid effects are NoSchedule, PreferNoSchedule and NoExecute.
   * @type {string}
   * @memberof IoK8sApiCoreV1Taint
   */
  effect: string;
  /**
   * Required. The taint key to be applied to a node.
   * @type {string}
   * @memberof IoK8sApiCoreV1Taint
   */
  key: string;
  /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   * @type {string}
   * @memberof IoK8sApiCoreV1Taint
   */
  timeAdded?: string;
  /**
   * The taint value corresponding to the taint key.
   * @type {string}
   * @memberof IoK8sApiCoreV1Taint
   */
  value?: string;
}
