/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionCondition,
  IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionNames,
} from './';

/**
 * CustomResourceDefinitionStatus indicates the state of the CustomResourceDefinition
 * @export
 * @interface IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionStatus
 */
export interface IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionStatus {
  /**
   *
   * @type {IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionNames}
   * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionStatus
   */
  acceptedNames?: IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionNames;
  /**
   * conditions indicate state for particular aspects of a CustomResourceDefinition
   * @type {Array<IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionCondition>}
   * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionStatus
   */
  conditions?: Array<IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionCondition>;
  /**
   * storedVersions lists all versions of CustomResources that were ever persisted. Tracking these versions allows a migration path for stored versions in etcd. The field is mutable so a migration controller can finish a migration to another version (ensuring no old objects are left in storage), and then remove the rest of the versions from this list. Versions may not be removed from `spec.versions` while they exist in this list.
   * @type {Array<string>}
   * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionStatus
   */
  storedVersions?: Array<string>;
}
