/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  IoK8sApiResourceV1beta2ResourceClaimSpec,
  IoK8sApimachineryPkgApisMetaV1ObjectMeta,
} from './';

/**
 * ResourceClaimTemplateSpec contains the metadata and fields for a ResourceClaim.
 * @export
 * @interface IoK8sApiResourceV1beta2ResourceClaimTemplateSpec
 */
export interface IoK8sApiResourceV1beta2ResourceClaimTemplateSpec {
  /**
   *
   * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
   * @memberof IoK8sApiResourceV1beta2ResourceClaimTemplateSpec
   */
  metadata?: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
  /**
   *
   * @type {IoK8sApiResourceV1beta2ResourceClaimSpec}
   * @memberof IoK8sApiResourceV1beta2ResourceClaimTemplateSpec
   */
  spec: IoK8sApiResourceV1beta2ResourceClaimSpec;
}
