/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
  IoK8sApiAutoscalingV2beta1HorizontalPodAutoscaler,
  IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerFromJSON,
  IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerToJSON,
  IoK8sApimachineryPkgApisMetaV1ListMeta,
  IoK8sApimachineryPkgApisMetaV1ListMetaFromJSON,
  IoK8sApimachineryPkgApisMetaV1ListMetaToJSON,
} from './';

/**
 * HorizontalPodAutoscaler is a list of horizontal pod autoscaler objects.
 * @export
 * @interface IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerList
 */
export interface IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerList {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   * @type {string}
   * @memberof IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerList
   */
  apiVersion?: string;
  /**
   * items is the list of horizontal pod autoscaler objects.
   * @type {Array<IoK8sApiAutoscalingV2beta1HorizontalPodAutoscaler>}
   * @memberof IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerList
   */
  items: Array<IoK8sApiAutoscalingV2beta1HorizontalPodAutoscaler>;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   * @type {string}
   * @memberof IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerList
   */
  kind?: string;
  /**
   *
   * @type {IoK8sApimachineryPkgApisMetaV1ListMeta}
   * @memberof IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerList
   */
  metadata?: IoK8sApimachineryPkgApisMetaV1ListMeta;
}

export function IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerListFromJSON(
  json: any,
): IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerList {
  return IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerListFromJSONTyped(json, false);
}

export function IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerListFromJSONTyped(
  json: any,
  _ignoreDiscriminator: boolean,
): IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerList {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    apiVersion: !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
    items: (json['items'] as Array<any>).map(
      IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerFromJSON,
    ),
    kind: !exists(json, 'kind') ? undefined : json['kind'],
    metadata: !exists(json, 'metadata')
      ? undefined
      : IoK8sApimachineryPkgApisMetaV1ListMetaFromJSON(json['metadata']),
  };
}

export function IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerListToJSON(
  value?: IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerList | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    apiVersion: value.apiVersion,
    items: (value.items as Array<any>).map(IoK8sApiAutoscalingV2beta1HorizontalPodAutoscalerToJSON),
    kind: value.kind,
    metadata: IoK8sApimachineryPkgApisMetaV1ListMetaToJSON(value.metadata),
  };
}
