/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  IoK8sApiCoreV1TopologySelectorLabelRequirement,
} from './';

/**
 * A topology selector term represents the result of label queries. A null or empty topology selector term matches no objects. The requirements of them are ANDed. It provides a subset of functionality as NodeSelectorTerm. This is an alpha feature and may change in the future.
 * @export
 * @interface IoK8sApiCoreV1TopologySelectorTerm
 */
export interface IoK8sApiCoreV1TopologySelectorTerm {
  /**
   * A list of topology selector requirements by labels.
   * @type {Array<IoK8sApiCoreV1TopologySelectorLabelRequirement>}
   * @memberof IoK8sApiCoreV1TopologySelectorTerm
   */
  matchLabelExpressions?: Array<IoK8sApiCoreV1TopologySelectorLabelRequirement>;
}
