/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
  IoK8sApiResourceV1alpha1ResourceClaimSpec,
  IoK8sApiResourceV1alpha1ResourceClaimSpecFromJSON,
  IoK8sApiResourceV1alpha1ResourceClaimSpecToJSON,
  IoK8sApimachineryPkgApisMetaV1ObjectMeta,
  IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSON,
  IoK8sApimachineryPkgApisMetaV1ObjectMetaToJSON,
} from './';

/**
 * ResourceClaimTemplateSpec contains the metadata and fields for a ResourceClaim.
 * @export
 * @interface IoK8sApiResourceV1alpha1ResourceClaimTemplateSpec
 */
export interface IoK8sApiResourceV1alpha1ResourceClaimTemplateSpec {
  /**
   *
   * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
   * @memberof IoK8sApiResourceV1alpha1ResourceClaimTemplateSpec
   */
  metadata?: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
  /**
   *
   * @type {IoK8sApiResourceV1alpha1ResourceClaimSpec}
   * @memberof IoK8sApiResourceV1alpha1ResourceClaimTemplateSpec
   */
  spec: IoK8sApiResourceV1alpha1ResourceClaimSpec;
}

export function IoK8sApiResourceV1alpha1ResourceClaimTemplateSpecFromJSON(
  json: any,
): IoK8sApiResourceV1alpha1ResourceClaimTemplateSpec {
  return IoK8sApiResourceV1alpha1ResourceClaimTemplateSpecFromJSONTyped(json, false);
}

export function IoK8sApiResourceV1alpha1ResourceClaimTemplateSpecFromJSONTyped(
  json: any,
  _ignoreDiscriminator: boolean,
): IoK8sApiResourceV1alpha1ResourceClaimTemplateSpec {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    metadata: !exists(json, 'metadata')
      ? undefined
      : IoK8sApimachineryPkgApisMetaV1ObjectMetaFromJSON(json['metadata']),
    spec: IoK8sApiResourceV1alpha1ResourceClaimSpecFromJSON(json['spec']),
  };
}

export function IoK8sApiResourceV1alpha1ResourceClaimTemplateSpecToJSON(
  value?: IoK8sApiResourceV1alpha1ResourceClaimTemplateSpec | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    metadata: IoK8sApimachineryPkgApisMetaV1ObjectMetaToJSON(value.metadata),
    spec: IoK8sApiResourceV1alpha1ResourceClaimSpecToJSON(value.spec),
  };
}
