/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  IoK8sApiStorageV1VolumeError,
} from './';

/**
 * VolumeAttachmentStatus is the status of a VolumeAttachment request.
 * @export
 * @interface IoK8sApiStorageV1VolumeAttachmentStatus
 */
export interface IoK8sApiStorageV1VolumeAttachmentStatus {
  /**
   *
   * @type {IoK8sApiStorageV1VolumeError}
   * @memberof IoK8sApiStorageV1VolumeAttachmentStatus
   */
  attachError?: IoK8sApiStorageV1VolumeError;
  /**
   * attached indicates the volume is successfully attached. This field must only be set by the entity completing the attach operation, i.e. the external-attacher.
   * @type {boolean}
   * @memberof IoK8sApiStorageV1VolumeAttachmentStatus
   */
  attached: boolean;
  /**
   * attachmentMetadata is populated with any information returned by the attach operation, upon successful attach, that must be passed into subsequent WaitForAttach or Mount calls. This field must only be set by the entity completing the attach operation, i.e. the external-attacher.
   * @type {{ [key: string]: string; }}
   * @memberof IoK8sApiStorageV1VolumeAttachmentStatus
   */
  attachmentMetadata?: { [key: string]: string };
  /**
   *
   * @type {IoK8sApiStorageV1VolumeError}
   * @memberof IoK8sApiStorageV1VolumeAttachmentStatus
   */
  detachError?: IoK8sApiStorageV1VolumeError;
}
