/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  IoK8sApiCoreV1ReplicationControllerCondition,
} from './';

/**
 * ReplicationControllerStatus represents the current status of a replication controller.
 * @export
 * @interface IoK8sApiCoreV1ReplicationControllerStatus
 */
export interface IoK8sApiCoreV1ReplicationControllerStatus {
  /**
   * The number of available replicas (ready for at least minReadySeconds) for this replication controller.
   * @type {number}
   * @memberof IoK8sApiCoreV1ReplicationControllerStatus
   */
  availableReplicas?: number;
  /**
   * Represents the latest available observations of a replication controller's current state.
   * @type {Array<IoK8sApiCoreV1ReplicationControllerCondition>}
   * @memberof IoK8sApiCoreV1ReplicationControllerStatus
   */
  conditions?: Array<IoK8sApiCoreV1ReplicationControllerCondition>;
  /**
   * The number of pods that have labels matching the labels of the pod template of the replication controller.
   * @type {number}
   * @memberof IoK8sApiCoreV1ReplicationControllerStatus
   */
  fullyLabeledReplicas?: number;
  /**
   * ObservedGeneration reflects the generation of the most recently observed replication controller.
   * @type {number}
   * @memberof IoK8sApiCoreV1ReplicationControllerStatus
   */
  observedGeneration?: number;
  /**
   * The number of ready replicas for this replication controller.
   * @type {number}
   * @memberof IoK8sApiCoreV1ReplicationControllerStatus
   */
  readyReplicas?: number;
  /**
   * Replicas is the most recently observed number of replicas. More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller#what-is-a-replicationcontroller
   * @type {number}
   * @memberof IoK8sApiCoreV1ReplicationControllerStatus
   */
  replicas: number;
}
