/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * PriorityLevelConfigurationReference contains information that points to the "request-priority" being used.
 * @export
 * @interface IoK8sApiFlowcontrolV1PriorityLevelConfigurationReference
 */
export interface IoK8sApiFlowcontrolV1PriorityLevelConfigurationReference {
  /**
   * `name` is the name of the priority level configuration being referenced Required.
   * @type {string}
   * @memberof IoK8sApiFlowcontrolV1PriorityLevelConfigurationReference
   */
  name: string;
}
