/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * PodReadinessGate contains the reference to a pod condition
 * @export
 * @interface IoK8sApiCoreV1PodReadinessGate
 */
export interface IoK8sApiCoreV1PodReadinessGate {
  /**
   * ConditionType refers to a condition in the pod's condition list with matching type.
   * @type {string}
   * @memberof IoK8sApiCoreV1PodReadinessGate
   */
  conditionType: string;
}
