/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  IoK8sApiCoreV1LoadBalancerStatus,
  IoK8sApimachineryPkgApisMetaV1Condition,
} from './';

/**
 * ServiceStatus represents the current status of a service.
 * @export
 * @interface IoK8sApiCoreV1ServiceStatus
 */
export interface IoK8sApiCoreV1ServiceStatus {
  /**
   * Current service state
   * @type {Array<IoK8sApimachineryPkgApisMetaV1Condition>}
   * @memberof IoK8sApiCoreV1ServiceStatus
   */
  conditions?: Array<IoK8sApimachineryPkgApisMetaV1Condition>;
  /**
   *
   * @type {IoK8sApiCoreV1LoadBalancerStatus}
   * @memberof IoK8sApiCoreV1ServiceStatus
   */
  loadBalancer?: IoK8sApiCoreV1LoadBalancerStatus;
}
