/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  IoK8sApiResourceV1beta2OpaqueDeviceConfiguration,
} from './';

/**
 * DeviceAllocationConfiguration gets embedded in an AllocationResult.
 * @export
 * @interface IoK8sApiResourceV1beta2DeviceAllocationConfiguration
 */
export interface IoK8sApiResourceV1beta2DeviceAllocationConfiguration {
  /**
   *
   * @type {IoK8sApiResourceV1beta2OpaqueDeviceConfiguration}
   * @memberof IoK8sApiResourceV1beta2DeviceAllocationConfiguration
   */
  opaque?: IoK8sApiResourceV1beta2OpaqueDeviceConfiguration;
  /**
   * Requests lists the names of requests where the configuration applies. If empty, its applies to all requests.
   *
   * References to subrequests must include the name of the main request and may include the subrequest using the format <main request>[/<subrequest>]. If just the main request is given, the configuration applies to all subrequests.
   * @type {Array<string>}
   * @memberof IoK8sApiResourceV1beta2DeviceAllocationConfiguration
   */
  requests?: Array<string>;
  /**
   * Source records whether the configuration comes from a class and thus is not something that a normal user would have been able to set or from a claim.
   * @type {string}
   * @memberof IoK8sApiResourceV1beta2DeviceAllocationConfiguration
   */
  source: string;
}
