/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  IoK8sApiCoreV1Namespace,
  IoK8sApimachineryPkgApisMetaV1ListMeta,
} from './';

/**
 * NamespaceList is a list of Namespaces.
 * @export
 * @interface IoK8sApiCoreV1NamespaceList
 */
export interface IoK8sApiCoreV1NamespaceList {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   * @type {string}
   * @memberof IoK8sApiCoreV1NamespaceList
   */
  apiVersion?: string;
  /**
   * Items is the list of Namespace objects in the list. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
   * @type {Array<IoK8sApiCoreV1Namespace>}
   * @memberof IoK8sApiCoreV1NamespaceList
   */
  items: Array<IoK8sApiCoreV1Namespace>;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   * @type {string}
   * @memberof IoK8sApiCoreV1NamespaceList
   */
  kind?: string;
  /**
   *
   * @type {IoK8sApimachineryPkgApisMetaV1ListMeta}
   * @memberof IoK8sApiCoreV1NamespaceList
   */
  metadata?: IoK8sApimachineryPkgApisMetaV1ListMeta;
}
