/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  IoK8sApiResourceV1alpha3BasicDevice,
} from './';

/**
 * Device represents one individual hardware instance that can be selected based on its attributes. Besides the name, exactly one field must be set.
 * @export
 * @interface IoK8sApiResourceV1alpha3Device
 */
export interface IoK8sApiResourceV1alpha3Device {
  /**
   *
   * @type {IoK8sApiResourceV1alpha3BasicDevice}
   * @memberof IoK8sApiResourceV1alpha3Device
   */
  basic?: IoK8sApiResourceV1alpha3BasicDevice;
  /**
   * Name is unique identifier among all devices managed by the driver in the pool. It must be a DNS label.
   * @type {string}
   * @memberof IoK8sApiResourceV1alpha3Device
   */
  name: string;
}
