/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  IoK8sApiCoreV1ConfigMapNodeConfigSource,
} from './';

/**
 * NodeConfigSource specifies a source of node configuration. Exactly one subfield (excluding metadata) must be non-nil. This API is deprecated since 1.22
 * @export
 * @interface IoK8sApiCoreV1NodeConfigSource
 */
export interface IoK8sApiCoreV1NodeConfigSource {
  /**
   *
   * @type {IoK8sApiCoreV1ConfigMapNodeConfigSource}
   * @memberof IoK8sApiCoreV1NodeConfigSource
   */
  configMap?: IoK8sApiCoreV1ConfigMapNodeConfigSource;
}
