/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * ExternalDocumentation allows referencing an external resource for extended documentation.
 * @export
 * @interface IoK8sApiextensionsApiserverPkgApisApiextensionsV1ExternalDocumentation
 */
export interface IoK8sApiextensionsApiserverPkgApisApiextensionsV1ExternalDocumentation {
  /**
   *
   * @type {string}
   * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1ExternalDocumentation
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof IoK8sApiextensionsApiserverPkgApisApiextensionsV1ExternalDocumentation
   */
  url?: string;
}
