/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IoK8sApiNetworkingV1IngressLoadBalancerStatus,
    IoK8sApiNetworkingV1IngressLoadBalancerStatusFromJSON,
    IoK8sApiNetworkingV1IngressLoadBalancerStatusFromJSONTyped,
    IoK8sApiNetworkingV1IngressLoadBalancerStatusToJSON,
} from './';

/**
 * IngressStatus describe the current state of the Ingress.
 * @export
 * @interface IoK8sApiNetworkingV1IngressStatus
 */
export interface IoK8sApiNetworkingV1IngressStatus {
    /**
     * 
     * @type {IoK8sApiNetworkingV1IngressLoadBalancerStatus}
     * @memberof IoK8sApiNetworkingV1IngressStatus
     */
    loadBalancer?: IoK8sApiNetworkingV1IngressLoadBalancerStatus;
}

export function IoK8sApiNetworkingV1IngressStatusFromJSON(json: any): IoK8sApiNetworkingV1IngressStatus {
    return IoK8sApiNetworkingV1IngressStatusFromJSONTyped(json, false);
}

export function IoK8sApiNetworkingV1IngressStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoK8sApiNetworkingV1IngressStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'loadBalancer': !exists(json, 'loadBalancer') ? undefined : IoK8sApiNetworkingV1IngressLoadBalancerStatusFromJSON(json['loadBalancer']),
    };
}

export function IoK8sApiNetworkingV1IngressStatusToJSON(value?: IoK8sApiNetworkingV1IngressStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'loadBalancer': IoK8sApiNetworkingV1IngressLoadBalancerStatusToJSON(value.loadBalancer),
    };
}

