/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IoK8sApiAppsV1RollingUpdateDeployment,
    IoK8sApiAppsV1RollingUpdateDeploymentFromJSON,
    IoK8sApiAppsV1RollingUpdateDeploymentFromJSONTyped,
    IoK8sApiAppsV1RollingUpdateDeploymentToJSON,
} from './';

/**
 * DeploymentStrategy describes how to replace existing pods with new ones.
 * @export
 * @interface IoK8sApiAppsV1DeploymentStrategy
 */
export interface IoK8sApiAppsV1DeploymentStrategy {
    /**
     * 
     * @type {IoK8sApiAppsV1RollingUpdateDeployment}
     * @memberof IoK8sApiAppsV1DeploymentStrategy
     */
    rollingUpdate?: IoK8sApiAppsV1RollingUpdateDeployment;
    /**
     * Type of deployment. Can be "Recreate" or "RollingUpdate". Default is RollingUpdate.
     * @type {string}
     * @memberof IoK8sApiAppsV1DeploymentStrategy
     */
    type?: string;
}

export function IoK8sApiAppsV1DeploymentStrategyFromJSON(json: any): IoK8sApiAppsV1DeploymentStrategy {
    return IoK8sApiAppsV1DeploymentStrategyFromJSONTyped(json, false);
}

export function IoK8sApiAppsV1DeploymentStrategyFromJSONTyped(json: any, _ignoreDiscriminator: boolean): IoK8sApiAppsV1DeploymentStrategy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rollingUpdate': !exists(json, 'rollingUpdate') ? undefined : IoK8sApiAppsV1RollingUpdateDeploymentFromJSON(json['rollingUpdate']),
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function IoK8sApiAppsV1DeploymentStrategyToJSON(value?: IoK8sApiAppsV1DeploymentStrategy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rollingUpdate': IoK8sApiAppsV1RollingUpdateDeploymentToJSON(value.rollingUpdate),
        'type': value.type,
    };
}

