/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  IoK8sApiAutoscalingV2beta2MetricIdentifier,
  IoK8sApiAutoscalingV2beta2MetricIdentifierFromJSON,
  IoK8sApiAutoscalingV2beta2MetricIdentifierToJSON,
  IoK8sApiAutoscalingV2beta2MetricValueStatus,
  IoK8sApiAutoscalingV2beta2MetricValueStatusFromJSON,
  IoK8sApiAutoscalingV2beta2MetricValueStatusToJSON,
} from './';

/**
 * ExternalMetricStatus indicates the current value of a global metric not associated with any Kubernetes object.
 * @export
 * @interface IoK8sApiAutoscalingV2beta2ExternalMetricStatus
 */
export interface IoK8sApiAutoscalingV2beta2ExternalMetricStatus {
  /**
   *
   * @type {IoK8sApiAutoscalingV2beta2MetricValueStatus}
   * @memberof IoK8sApiAutoscalingV2beta2ExternalMetricStatus
   */
  current: IoK8sApiAutoscalingV2beta2MetricValueStatus;
  /**
   *
   * @type {IoK8sApiAutoscalingV2beta2MetricIdentifier}
   * @memberof IoK8sApiAutoscalingV2beta2ExternalMetricStatus
   */
  metric: IoK8sApiAutoscalingV2beta2MetricIdentifier;
}

export function IoK8sApiAutoscalingV2beta2ExternalMetricStatusFromJSON(
  json: any,
): IoK8sApiAutoscalingV2beta2ExternalMetricStatus {
  return IoK8sApiAutoscalingV2beta2ExternalMetricStatusFromJSONTyped(json, false);
}

export function IoK8sApiAutoscalingV2beta2ExternalMetricStatusFromJSONTyped(
  json: any,
  _ignoreDiscriminator: boolean,
): IoK8sApiAutoscalingV2beta2ExternalMetricStatus {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    current: IoK8sApiAutoscalingV2beta2MetricValueStatusFromJSON(json['current']),
    metric: IoK8sApiAutoscalingV2beta2MetricIdentifierFromJSON(json['metric']),
  };
}

export function IoK8sApiAutoscalingV2beta2ExternalMetricStatusToJSON(
  value?: IoK8sApiAutoscalingV2beta2ExternalMetricStatus | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    current: IoK8sApiAutoscalingV2beta2MetricValueStatusToJSON(value.current),
    metric: IoK8sApiAutoscalingV2beta2MetricIdentifierToJSON(value.metric),
  };
}
