/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * LinuxContainerUser represents user identity information in Linux containers
 * @export
 * @interface IoK8sApiCoreV1LinuxContainerUser
 */
export interface IoK8sApiCoreV1LinuxContainerUser {
  /**
   * GID is the primary gid initially attached to the first process in the container
   * @type {number}
   * @memberof IoK8sApiCoreV1LinuxContainerUser
   */
  gid: number;
  /**
   * SupplementalGroups are the supplemental groups initially attached to the first process in the container
   * @type {Array<number>}
   * @memberof IoK8sApiCoreV1LinuxContainerUser
   */
  supplementalGroups?: Array<number>;
  /**
   * UID is the primary uid initially attached to the first process in the container
   * @type {number}
   * @memberof IoK8sApiCoreV1LinuxContainerUser
   */
  uid: number;
}
