/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  IoK8sApiAutoscalingV2beta2CrossVersionObjectReference,
  IoK8sApiAutoscalingV2beta2CrossVersionObjectReferenceFromJSON,
  IoK8sApiAutoscalingV2beta2CrossVersionObjectReferenceToJSON,
  IoK8sApiAutoscalingV2beta2MetricIdentifier,
  IoK8sApiAutoscalingV2beta2MetricIdentifierFromJSON,
  IoK8sApiAutoscalingV2beta2MetricIdentifierToJSON,
  IoK8sApiAutoscalingV2beta2MetricValueStatus,
  IoK8sApiAutoscalingV2beta2MetricValueStatusFromJSON,
  IoK8sApiAutoscalingV2beta2MetricValueStatusToJSON,
} from './';

/**
 * ObjectMetricStatus indicates the current value of a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).
 * @export
 * @interface IoK8sApiAutoscalingV2beta2ObjectMetricStatus
 */
export interface IoK8sApiAutoscalingV2beta2ObjectMetricStatus {
  /**
   *
   * @type {IoK8sApiAutoscalingV2beta2MetricValueStatus}
   * @memberof IoK8sApiAutoscalingV2beta2ObjectMetricStatus
   */
  current: IoK8sApiAutoscalingV2beta2MetricValueStatus;
  /**
   *
   * @type {IoK8sApiAutoscalingV2beta2CrossVersionObjectReference}
   * @memberof IoK8sApiAutoscalingV2beta2ObjectMetricStatus
   */
  describedObject: IoK8sApiAutoscalingV2beta2CrossVersionObjectReference;
  /**
   *
   * @type {IoK8sApiAutoscalingV2beta2MetricIdentifier}
   * @memberof IoK8sApiAutoscalingV2beta2ObjectMetricStatus
   */
  metric: IoK8sApiAutoscalingV2beta2MetricIdentifier;
}

export function IoK8sApiAutoscalingV2beta2ObjectMetricStatusFromJSON(
  json: any,
): IoK8sApiAutoscalingV2beta2ObjectMetricStatus {
  return IoK8sApiAutoscalingV2beta2ObjectMetricStatusFromJSONTyped(json, false);
}

export function IoK8sApiAutoscalingV2beta2ObjectMetricStatusFromJSONTyped(
  json: any,
  _ignoreDiscriminator: boolean,
): IoK8sApiAutoscalingV2beta2ObjectMetricStatus {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    current: IoK8sApiAutoscalingV2beta2MetricValueStatusFromJSON(json['current']),
    describedObject: IoK8sApiAutoscalingV2beta2CrossVersionObjectReferenceFromJSON(
      json['describedObject'],
    ),
    metric: IoK8sApiAutoscalingV2beta2MetricIdentifierFromJSON(json['metric']),
  };
}

export function IoK8sApiAutoscalingV2beta2ObjectMetricStatusToJSON(
  value?: IoK8sApiAutoscalingV2beta2ObjectMetricStatus | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    current: IoK8sApiAutoscalingV2beta2MetricValueStatusToJSON(value.current),
    describedObject: IoK8sApiAutoscalingV2beta2CrossVersionObjectReferenceToJSON(
      value.describedObject,
    ),
    metric: IoK8sApiAutoscalingV2beta2MetricIdentifierToJSON(value.metric),
  };
}
