/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  IoK8sApiCoreV1EventSeries,
  IoK8sApiCoreV1EventSource,
  IoK8sApiCoreV1ObjectReference,
  IoK8sApimachineryPkgApisMetaV1ObjectMeta,
} from './';

/**
 * Event is a report of an event somewhere in the cluster.  Events have a limited retention time and triggers and messages may evolve with time.  Event consumers should not rely on the timing of an event with a given Reason reflecting a consistent underlying trigger, or the continued existence of events with that Reason.  Events should be treated as informative, best-effort, supplemental data.
 * @export
 * @interface IoK8sApiCoreV1Event
 */
export interface IoK8sApiCoreV1Event {
  /**
   * What action was taken/failed regarding to the Regarding object.
   * @type {string}
   * @memberof IoK8sApiCoreV1Event
   */
  action?: string;
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   * @type {string}
   * @memberof IoK8sApiCoreV1Event
   */
  apiVersion?: string;
  /**
   * The number of times this event has occurred.
   * @type {number}
   * @memberof IoK8sApiCoreV1Event
   */
  count?: number;
  /**
   * MicroTime is version of Time with microsecond level precision.
   * @type {string}
   * @memberof IoK8sApiCoreV1Event
   */
  eventTime?: string;
  /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   * @type {string}
   * @memberof IoK8sApiCoreV1Event
   */
  firstTimestamp?: string;
  /**
   *
   * @type {IoK8sApiCoreV1ObjectReference}
   * @memberof IoK8sApiCoreV1Event
   */
  involvedObject: IoK8sApiCoreV1ObjectReference;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   * @type {string}
   * @memberof IoK8sApiCoreV1Event
   */
  kind?: string;
  /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   * @type {string}
   * @memberof IoK8sApiCoreV1Event
   */
  lastTimestamp?: string;
  /**
   * A human-readable description of the status of this operation.
   * @type {string}
   * @memberof IoK8sApiCoreV1Event
   */
  message?: string;
  /**
   *
   * @type {IoK8sApimachineryPkgApisMetaV1ObjectMeta}
   * @memberof IoK8sApiCoreV1Event
   */
  metadata: IoK8sApimachineryPkgApisMetaV1ObjectMeta;
  /**
   * This should be a short, machine understandable string that gives the reason for the transition into the object's current status.
   * @type {string}
   * @memberof IoK8sApiCoreV1Event
   */
  reason?: string;
  /**
   *
   * @type {IoK8sApiCoreV1ObjectReference}
   * @memberof IoK8sApiCoreV1Event
   */
  related?: IoK8sApiCoreV1ObjectReference;
  /**
   * Name of the controller that emitted this Event, e.g. `kubernetes.io/kubelet`.
   * @type {string}
   * @memberof IoK8sApiCoreV1Event
   */
  reportingComponent?: string;
  /**
   * ID of the controller instance, e.g. `kubelet-xyzf`.
   * @type {string}
   * @memberof IoK8sApiCoreV1Event
   */
  reportingInstance?: string;
  /**
   *
   * @type {IoK8sApiCoreV1EventSeries}
   * @memberof IoK8sApiCoreV1Event
   */
  series?: IoK8sApiCoreV1EventSeries;
  /**
   *
   * @type {IoK8sApiCoreV1EventSource}
   * @memberof IoK8sApiCoreV1Event
   */
  source?: IoK8sApiCoreV1EventSource;
  /**
   * Type of this event (Normal, Warning), new types could be added in the future
   * @type {string}
   * @memberof IoK8sApiCoreV1Event
   */
  type?: string;
}
