/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * DaemonEndpoint contains information about a single Daemon endpoint.
 * @export
 * @interface IoK8sApiCoreV1DaemonEndpoint
 */
export interface IoK8sApiCoreV1DaemonEndpoint {
  /**
   * Port number of the given endpoint.
   * @type {number}
   * @memberof IoK8sApiCoreV1DaemonEndpoint
   */
  port: number;
}
