/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  IoK8sApiCoreV1NodeSelector,
  IoK8sApiResourceV1beta1DeviceAttribute,
  IoK8sApiResourceV1beta1DeviceCapacity,
  IoK8sApiResourceV1beta1DeviceCounterConsumption,
  IoK8sApiResourceV1beta1DeviceTaint,
} from './';

/**
 * BasicDevice defines one device instance.
 * @export
 * @interface IoK8sApiResourceV1beta1BasicDevice
 */
export interface IoK8sApiResourceV1beta1BasicDevice {
  /**
   * AllNodes indicates that all nodes have access to the device.
   *
   * Must only be set if Spec.PerDeviceNodeSelection is set to true. At most one of NodeName, NodeSelector and AllNodes can be set.
   * @type {boolean}
   * @memberof IoK8sApiResourceV1beta1BasicDevice
   */
  allNodes?: boolean;
  /**
   * Attributes defines the set of attributes for this device. The name of each attribute must be unique in that set.
   *
   * The maximum number of attributes and capacities combined is 32.
   * @type {{ [key: string]: IoK8sApiResourceV1beta1DeviceAttribute; }}
   * @memberof IoK8sApiResourceV1beta1BasicDevice
   */
  attributes?: { [key: string]: IoK8sApiResourceV1beta1DeviceAttribute };
  /**
   * Capacity defines the set of capacities for this device. The name of each capacity must be unique in that set.
   *
   * The maximum number of attributes and capacities combined is 32.
   * @type {{ [key: string]: IoK8sApiResourceV1beta1DeviceCapacity; }}
   * @memberof IoK8sApiResourceV1beta1BasicDevice
   */
  capacity?: { [key: string]: IoK8sApiResourceV1beta1DeviceCapacity };
  /**
   * ConsumesCounters defines a list of references to sharedCounters and the set of counters that the device will consume from those counter sets.
   *
   * There can only be a single entry per counterSet.
   *
   * The total number of device counter consumption entries must be <= 32. In addition, the total number in the entire ResourceSlice must be <= 1024 (for example, 64 devices with 16 counters each).
   * @type {Array<IoK8sApiResourceV1beta1DeviceCounterConsumption>}
   * @memberof IoK8sApiResourceV1beta1BasicDevice
   */
  consumesCounters?: Array<IoK8sApiResourceV1beta1DeviceCounterConsumption>;
  /**
   * NodeName identifies the node where the device is available.
   *
   * Must only be set if Spec.PerDeviceNodeSelection is set to true. At most one of NodeName, NodeSelector and AllNodes can be set.
   * @type {string}
   * @memberof IoK8sApiResourceV1beta1BasicDevice
   */
  nodeName?: string;
  /**
   *
   * @type {IoK8sApiCoreV1NodeSelector}
   * @memberof IoK8sApiResourceV1beta1BasicDevice
   */
  nodeSelector?: IoK8sApiCoreV1NodeSelector;
  /**
   * If specified, these are the driver-defined taints.
   *
   * The maximum number of taints is 4.
   *
   * This is an alpha field and requires enabling the DRADeviceTaints feature gate.
   * @type {Array<IoK8sApiResourceV1beta1DeviceTaint>}
   * @memberof IoK8sApiResourceV1beta1BasicDevice
   */
  taints?: Array<IoK8sApiResourceV1beta1DeviceTaint>;
}
