/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  IoK8sApiCoreV1AWSElasticBlockStoreVolumeSource,
  IoK8sApiCoreV1AzureDiskVolumeSource,
  IoK8sApiCoreV1AzureFileVolumeSource,
  IoK8sApiCoreV1CSIVolumeSource,
  IoK8sApiCoreV1CephFSVolumeSource,
  IoK8sApiCoreV1CinderVolumeSource,
  IoK8sApiCoreV1ConfigMapVolumeSource,
  IoK8sApiCoreV1DownwardAPIVolumeSource,
  IoK8sApiCoreV1EmptyDirVolumeSource,
  IoK8sApiCoreV1EphemeralVolumeSource,
  IoK8sApiCoreV1FCVolumeSource,
  IoK8sApiCoreV1FlexVolumeSource,
  IoK8sApiCoreV1FlockerVolumeSource,
  IoK8sApiCoreV1GCEPersistentDiskVolumeSource,
  IoK8sApiCoreV1GitRepoVolumeSource,
  IoK8sApiCoreV1GlusterfsVolumeSource,
  IoK8sApiCoreV1HostPathVolumeSource,
  IoK8sApiCoreV1ISCSIVolumeSource,
  IoK8sApiCoreV1ImageVolumeSource,
  IoK8sApiCoreV1NFSVolumeSource,
  IoK8sApiCoreV1PersistentVolumeClaimVolumeSource,
  IoK8sApiCoreV1PhotonPersistentDiskVolumeSource,
  IoK8sApiCoreV1PortworxVolumeSource,
  IoK8sApiCoreV1ProjectedVolumeSource,
  IoK8sApiCoreV1QuobyteVolumeSource,
  IoK8sApiCoreV1RBDVolumeSource,
  IoK8sApiCoreV1ScaleIOVolumeSource,
  IoK8sApiCoreV1SecretVolumeSource,
  IoK8sApiCoreV1StorageOSVolumeSource,
  IoK8sApiCoreV1VsphereVirtualDiskVolumeSource,
} from './';

/**
 * Volume represents a named volume in a pod that may be accessed by any container in the pod.
 * @export
 * @interface IoK8sApiCoreV1Volume
 */
export interface IoK8sApiCoreV1Volume {
  /**
   *
   * @type {IoK8sApiCoreV1AWSElasticBlockStoreVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  awsElasticBlockStore?: IoK8sApiCoreV1AWSElasticBlockStoreVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1AzureDiskVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  azureDisk?: IoK8sApiCoreV1AzureDiskVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1AzureFileVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  azureFile?: IoK8sApiCoreV1AzureFileVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1CephFSVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  cephfs?: IoK8sApiCoreV1CephFSVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1CinderVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  cinder?: IoK8sApiCoreV1CinderVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1ConfigMapVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  configMap?: IoK8sApiCoreV1ConfigMapVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1CSIVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  csi?: IoK8sApiCoreV1CSIVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1DownwardAPIVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  downwardAPI?: IoK8sApiCoreV1DownwardAPIVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1EmptyDirVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  emptyDir?: IoK8sApiCoreV1EmptyDirVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1EphemeralVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  ephemeral?: IoK8sApiCoreV1EphemeralVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1FCVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  fc?: IoK8sApiCoreV1FCVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1FlexVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  flexVolume?: IoK8sApiCoreV1FlexVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1FlockerVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  flocker?: IoK8sApiCoreV1FlockerVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1GCEPersistentDiskVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  gcePersistentDisk?: IoK8sApiCoreV1GCEPersistentDiskVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1GitRepoVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  gitRepo?: IoK8sApiCoreV1GitRepoVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1GlusterfsVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  glusterfs?: IoK8sApiCoreV1GlusterfsVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1HostPathVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  hostPath?: IoK8sApiCoreV1HostPathVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1ImageVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  image?: IoK8sApiCoreV1ImageVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1ISCSIVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  iscsi?: IoK8sApiCoreV1ISCSIVolumeSource;
  /**
   * name of the volume. Must be a DNS_LABEL and unique within the pod. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
   * @type {string}
   * @memberof IoK8sApiCoreV1Volume
   */
  name: string;
  /**
   *
   * @type {IoK8sApiCoreV1NFSVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  nfs?: IoK8sApiCoreV1NFSVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1PersistentVolumeClaimVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  persistentVolumeClaim?: IoK8sApiCoreV1PersistentVolumeClaimVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1PhotonPersistentDiskVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  photonPersistentDisk?: IoK8sApiCoreV1PhotonPersistentDiskVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1PortworxVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  portworxVolume?: IoK8sApiCoreV1PortworxVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1ProjectedVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  projected?: IoK8sApiCoreV1ProjectedVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1QuobyteVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  quobyte?: IoK8sApiCoreV1QuobyteVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1RBDVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  rbd?: IoK8sApiCoreV1RBDVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1ScaleIOVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  scaleIO?: IoK8sApiCoreV1ScaleIOVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1SecretVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  secret?: IoK8sApiCoreV1SecretVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1StorageOSVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  storageos?: IoK8sApiCoreV1StorageOSVolumeSource;
  /**
   *
   * @type {IoK8sApiCoreV1VsphereVirtualDiskVolumeSource}
   * @memberof IoK8sApiCoreV1Volume
   */
  vsphereVolume?: IoK8sApiCoreV1VsphereVirtualDiskVolumeSource;
}
