/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  IoK8sApiResourceV1beta1OpaqueDeviceConfiguration,
} from './';

/**
 * DeviceClassConfiguration is used in DeviceClass.
 * @export
 * @interface IoK8sApiResourceV1beta1DeviceClassConfiguration
 */
export interface IoK8sApiResourceV1beta1DeviceClassConfiguration {
  /**
   *
   * @type {IoK8sApiResourceV1beta1OpaqueDeviceConfiguration}
   * @memberof IoK8sApiResourceV1beta1DeviceClassConfiguration
   */
  opaque?: IoK8sApiResourceV1beta1OpaqueDeviceConfiguration;
}
