/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * VolumeError captures an error encountered during a volume operation.
 * @export
 * @interface IoK8sApiStorageV1VolumeError
 */
export interface IoK8sApiStorageV1VolumeError {
  /**
   * errorCode is a numeric gRPC code representing the error encountered during Attach or Detach operations.
   *
   * This is an optional, alpha field that requires the MutableCSINodeAllocatableCount feature gate being enabled to be set.
   * @type {number}
   * @memberof IoK8sApiStorageV1VolumeError
   */
  errorCode?: number;
  /**
   * message represents the error encountered during Attach or Detach operation. This string may be logged, so it should not contain sensitive information.
   * @type {string}
   * @memberof IoK8sApiStorageV1VolumeError
   */
  message?: string;
  /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   * @type {string}
   * @memberof IoK8sApiStorageV1VolumeError
   */
  time?: string;
}
