/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  IoK8sApiCoreV1NodeSelectorRequirement,
} from './';

/**
 * A null or empty node selector term matches no objects. The requirements of them are ANDed. The TopologySelectorTerm type implements a subset of the NodeSelectorTerm.
 * @export
 * @interface IoK8sApiCoreV1NodeSelectorTerm
 */
export interface IoK8sApiCoreV1NodeSelectorTerm {
  /**
   * A list of node selector requirements by node's labels.
   * @type {Array<IoK8sApiCoreV1NodeSelectorRequirement>}
   * @memberof IoK8sApiCoreV1NodeSelectorTerm
   */
  matchExpressions?: Array<IoK8sApiCoreV1NodeSelectorRequirement>;
  /**
   * A list of node selector requirements by node's fields.
   * @type {Array<IoK8sApiCoreV1NodeSelectorRequirement>}
   * @memberof IoK8sApiCoreV1NodeSelectorTerm
   */
  matchFields?: Array<IoK8sApiCoreV1NodeSelectorRequirement>;
}
