/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  IoK8sApiCoreV1ClientIPConfig,
} from './';

/**
 * SessionAffinityConfig represents the configurations of session affinity.
 * @export
 * @interface IoK8sApiCoreV1SessionAffinityConfig
 */
export interface IoK8sApiCoreV1SessionAffinityConfig {
  /**
   *
   * @type {IoK8sApiCoreV1ClientIPConfig}
   * @memberof IoK8sApiCoreV1SessionAffinityConfig
   */
  clientIP?: IoK8sApiCoreV1ClientIPConfig;
}
