/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IoK8sApiCoreV1ConfigMapNodeConfigSource,
    IoK8sApiCoreV1ConfigMapNodeConfigSourceFromJSON,
    IoK8sApiCoreV1ConfigMapNodeConfigSourceFromJSONTyped,
    IoK8sApiCoreV1ConfigMapNodeConfigSourceToJSON,
} from './';

/**
 * NodeConfigSource specifies a source of node configuration. Exactly one subfield (excluding metadata) must be non-nil. This API is deprecated since 1.22
 * @export
 * @interface IoK8sApiCoreV1NodeConfigSource
 */
export interface IoK8sApiCoreV1NodeConfigSource {
    /**
     * 
     * @type {IoK8sApiCoreV1ConfigMapNodeConfigSource}
     * @memberof IoK8sApiCoreV1NodeConfigSource
     */
    configMap?: IoK8sApiCoreV1ConfigMapNodeConfigSource;
}

export function IoK8sApiCoreV1NodeConfigSourceFromJSON(json: any): IoK8sApiCoreV1NodeConfigSource {
    return IoK8sApiCoreV1NodeConfigSourceFromJSONTyped(json, false);
}

export function IoK8sApiCoreV1NodeConfigSourceFromJSONTyped(json: any, _ignoreDiscriminator: boolean): IoK8sApiCoreV1NodeConfigSource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'configMap': !exists(json, 'configMap') ? undefined : IoK8sApiCoreV1ConfigMapNodeConfigSourceFromJSON(json['configMap']),
    };
}

export function IoK8sApiCoreV1NodeConfigSourceToJSON(value?: IoK8sApiCoreV1NodeConfigSource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'configMap': IoK8sApiCoreV1ConfigMapNodeConfigSourceToJSON(value.configMap),
    };
}

