/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * DeviceAttribute must have exactly one field set.
 * @export
 * @interface IoK8sApiResourceV1alpha3DeviceAttribute
 */
export interface IoK8sApiResourceV1alpha3DeviceAttribute {
  /**
   * BoolValue is a true/false value.
   * @type {boolean}
   * @memberof IoK8sApiResourceV1alpha3DeviceAttribute
   */
  bool?: boolean;
  /**
   * IntValue is a number.
   * @type {number}
   * @memberof IoK8sApiResourceV1alpha3DeviceAttribute
   */
  _int?: number;
  /**
   * StringValue is a string. Must not be longer than 64 characters.
   * @type {string}
   * @memberof IoK8sApiResourceV1alpha3DeviceAttribute
   */
  string?: string;
  /**
   * VersionValue is a semantic version according to semver.org spec 2.0.0. Must not be longer than 64 characters.
   * @type {string}
   * @memberof IoK8sApiResourceV1alpha3DeviceAttribute
   */
  version?: string;
}
