/* tslint:disable */
/* eslint-disable */
/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unversioned
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
  IoK8sApiStorageV1beta1CSIStorageCapacity,
  IoK8sApiStorageV1beta1CSIStorageCapacityFromJSON,
  IoK8sApiStorageV1beta1CSIStorageCapacityToJSON,
  IoK8sApimachineryPkgApisMetaV1ListMeta,
  IoK8sApimachineryPkgApisMetaV1ListMetaFromJSON,
  IoK8sApimachineryPkgApisMetaV1ListMetaToJSON,
} from './';

/**
 * CSIStorageCapacityList is a collection of CSIStorageCapacity objects.
 * @export
 * @interface IoK8sApiStorageV1beta1CSIStorageCapacityList
 */
export interface IoK8sApiStorageV1beta1CSIStorageCapacityList {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   * @type {string}
   * @memberof IoK8sApiStorageV1beta1CSIStorageCapacityList
   */
  apiVersion?: string;
  /**
   * Items is the list of CSIStorageCapacity objects.
   * @type {Array<IoK8sApiStorageV1beta1CSIStorageCapacity>}
   * @memberof IoK8sApiStorageV1beta1CSIStorageCapacityList
   */
  items: Array<IoK8sApiStorageV1beta1CSIStorageCapacity>;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   * @type {string}
   * @memberof IoK8sApiStorageV1beta1CSIStorageCapacityList
   */
  kind?: string;
  /**
   *
   * @type {IoK8sApimachineryPkgApisMetaV1ListMeta}
   * @memberof IoK8sApiStorageV1beta1CSIStorageCapacityList
   */
  metadata?: IoK8sApimachineryPkgApisMetaV1ListMeta;
}

export function IoK8sApiStorageV1beta1CSIStorageCapacityListFromJSON(
  json: any,
): IoK8sApiStorageV1beta1CSIStorageCapacityList {
  return IoK8sApiStorageV1beta1CSIStorageCapacityListFromJSONTyped(json, false);
}

export function IoK8sApiStorageV1beta1CSIStorageCapacityListFromJSONTyped(
  json: any,
  _ignoreDiscriminator: boolean,
): IoK8sApiStorageV1beta1CSIStorageCapacityList {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    apiVersion: !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
    items: (json['items'] as Array<any>).map(IoK8sApiStorageV1beta1CSIStorageCapacityFromJSON),
    kind: !exists(json, 'kind') ? undefined : json['kind'],
    metadata: !exists(json, 'metadata')
      ? undefined
      : IoK8sApimachineryPkgApisMetaV1ListMetaFromJSON(json['metadata']),
  };
}

export function IoK8sApiStorageV1beta1CSIStorageCapacityListToJSON(
  value?: IoK8sApiStorageV1beta1CSIStorageCapacityList | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    apiVersion: value.apiVersion,
    items: (value.items as Array<any>).map(IoK8sApiStorageV1beta1CSIStorageCapacityToJSON),
    kind: value.kind,
    metadata: IoK8sApimachineryPkgApisMetaV1ListMetaToJSON(value.metadata),
  };
}
