/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { K8sIoApimachineryPkgApisMetaV1APIResource } from './K8sIoApimachineryPkgApisMetaV1APIResource';
/**
 * APIResourceList is a list of APIResource, it is used to expose the name of the resources supported in a specific group and version, and if the resource is namespaced.
 * @export
 * @interface K8sIoApimachineryPkgApisMetaV1APIResourceList
 */
export interface K8sIoApimachineryPkgApisMetaV1APIResourceList {
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   * @type {string}
   * @memberof K8sIoApimachineryPkgApisMetaV1APIResourceList
   */
  apiVersion?: string;
  /**
   * groupVersion is the group and version this APIResourceList is for.
   * @type {string}
   * @memberof K8sIoApimachineryPkgApisMetaV1APIResourceList
   */
  groupVersion: string;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   * @type {string}
   * @memberof K8sIoApimachineryPkgApisMetaV1APIResourceList
   */
  kind?: string;
  /**
   * resources contains the name of the resources and if they are namespaced.
   * @type {Array<K8sIoApimachineryPkgApisMetaV1APIResource>}
   * @memberof K8sIoApimachineryPkgApisMetaV1APIResourceList
   */
  resources: Array<K8sIoApimachineryPkgApisMetaV1APIResource>;
}

/**
 * Check if a given object implements the K8sIoApimachineryPkgApisMetaV1APIResourceList interface.
 */
