/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { K8sIoApiCoreV1NodeAffinity } from './K8sIoApiCoreV1NodeAffinity';
import type { K8sIoApiCoreV1PodAffinity } from './K8sIoApiCoreV1PodAffinity';
import type { K8sIoApiCoreV1PodAntiAffinity } from './K8sIoApiCoreV1PodAntiAffinity';
/**
 * Affinity is a group of affinity scheduling rules.
 * @export
 * @interface K8sIoApiCoreV1Affinity
 */
export interface K8sIoApiCoreV1Affinity {
  /**
   *
   * @type {K8sIoApiCoreV1NodeAffinity}
   * @memberof K8sIoApiCoreV1Affinity
   */
  nodeAffinity?: K8sIoApiCoreV1NodeAffinity;
  /**
   *
   * @type {K8sIoApiCoreV1PodAffinity}
   * @memberof K8sIoApiCoreV1Affinity
   */
  podAffinity?: K8sIoApiCoreV1PodAffinity;
  /**
   *
   * @type {K8sIoApiCoreV1PodAntiAffinity}
   * @memberof K8sIoApiCoreV1Affinity
   */
  podAntiAffinity?: K8sIoApiCoreV1PodAntiAffinity;
}

/**
 * Check if a given object implements the K8sIoApiCoreV1Affinity interface.
 */
