/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface V1AccessCredentialSecretSource
 */
export interface V1AccessCredentialSecretSource {
  /**
   * SecretName represents the name of the secret in the VMI's namespace
   * @type {string}
   * @memberof V1AccessCredentialSecretSource
   */
  secretName: string;
}

/**
 * Check if a given object implements the V1AccessCredentialSecretSource interface.
 */
