/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
  V1alpha1Condition,
  V1alpha1ConditionFromJSON,
  V1alpha1ConditionToJSON,
  V1alpha1VirtualMachineExportLinks,
  V1alpha1VirtualMachineExportLinksFromJSON,
  V1alpha1VirtualMachineExportLinksToJSON,
} from './';

/**
 * VirtualMachineExportStatus is the status for a VirtualMachineExport resource
 * @export
 * @interface V1alpha1VirtualMachineExportStatus
 */
export interface V1alpha1VirtualMachineExportStatus {
  /**
   *
   * @type {Array<V1alpha1Condition>}
   * @memberof V1alpha1VirtualMachineExportStatus
   */
  conditions?: Array<V1alpha1Condition>;
  /**
   *
   * @type {V1alpha1VirtualMachineExportLinks}
   * @memberof V1alpha1VirtualMachineExportStatus
   */
  links?: V1alpha1VirtualMachineExportLinks;
  /**
   *
   * @type {string}
   * @memberof V1alpha1VirtualMachineExportStatus
   */
  phase?: string;
  /**
   * ServiceName is the name of the service created associated with the Virtual Machine export. It will be used to create the internal URLs for downloading the images
   * @type {string}
   * @memberof V1alpha1VirtualMachineExportStatus
   */
  serviceName?: string;
  /**
   * TokenSecretRef is the name of the secret that contains the token used by the export server pod
   * @type {string}
   * @memberof V1alpha1VirtualMachineExportStatus
   */
  tokenSecretRef?: string;
  /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   * @type {string}
   * @memberof V1alpha1VirtualMachineExportStatus
   */
  ttlExpirationTime?: string;
}

export function V1alpha1VirtualMachineExportStatusFromJSON(
  json: any,
): V1alpha1VirtualMachineExportStatus {
  return V1alpha1VirtualMachineExportStatusFromJSONTyped(json, false);
}

export function V1alpha1VirtualMachineExportStatusFromJSONTyped(
  json: any,
  _ignoreDiscriminator: boolean,
): V1alpha1VirtualMachineExportStatus {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    conditions: !exists(json, 'conditions')
      ? undefined
      : (json['conditions'] as Array<any>).map(V1alpha1ConditionFromJSON),
    links: !exists(json, 'links')
      ? undefined
      : V1alpha1VirtualMachineExportLinksFromJSON(json['links']),
    phase: !exists(json, 'phase') ? undefined : json['phase'],
    serviceName: !exists(json, 'serviceName') ? undefined : json['serviceName'],
    tokenSecretRef: !exists(json, 'tokenSecretRef') ? undefined : json['tokenSecretRef'],
    ttlExpirationTime: !exists(json, 'ttlExpirationTime') ? undefined : json['ttlExpirationTime'],
  };
}

export function V1alpha1VirtualMachineExportStatusToJSON(
  value?: V1alpha1VirtualMachineExportStatus | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    conditions:
      value.conditions === undefined
        ? undefined
        : (value.conditions as Array<any>).map(V1alpha1ConditionToJSON),
    links: V1alpha1VirtualMachineExportLinksToJSON(value.links),
    phase: value.phase,
    serviceName: value.serviceName,
    tokenSecretRef: value.tokenSecretRef,
    ttlExpirationTime: value.ttlExpirationTime === undefined ? undefined : value.ttlExpirationTime,
  };
}
