/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
  K8sIoApiCoreV1TypedLocalObjectReference,
  K8sIoApiCoreV1TypedLocalObjectReferenceFromJSON,
  K8sIoApiCoreV1TypedLocalObjectReferenceToJSON,
} from './';

/**
 * VirtualMachineRestoreSpec is the spec for a VirtualMachineRestoreresource
 * @export
 * @interface V1alpha1VirtualMachineRestoreSpec
 */
export interface V1alpha1VirtualMachineRestoreSpec {
  /**
   *
   * @type {K8sIoApiCoreV1TypedLocalObjectReference}
   * @memberof V1alpha1VirtualMachineRestoreSpec
   */
  target: K8sIoApiCoreV1TypedLocalObjectReference;
  /**
   *
   * @type {string}
   * @memberof V1alpha1VirtualMachineRestoreSpec
   */
  virtualMachineSnapshotName: string;
}

export function V1alpha1VirtualMachineRestoreSpecFromJSON(
  json: any,
): V1alpha1VirtualMachineRestoreSpec {
  return V1alpha1VirtualMachineRestoreSpecFromJSONTyped(json, false);
}

export function V1alpha1VirtualMachineRestoreSpecFromJSONTyped(
  json: any,
  _ignoreDiscriminator: boolean,
): V1alpha1VirtualMachineRestoreSpec {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    target: K8sIoApiCoreV1TypedLocalObjectReferenceFromJSON(json['target']),
    virtualMachineSnapshotName: json['virtualMachineSnapshotName'],
  };
}

export function V1alpha1VirtualMachineRestoreSpecToJSON(
  value?: V1alpha1VirtualMachineRestoreSpec | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    target: K8sIoApiCoreV1TypedLocalObjectReferenceToJSON(value.target),
    virtualMachineSnapshotName: value.virtualMachineSnapshotName,
  };
}
