/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 * CPUPreferences contains various optional CPU preferences.
 * @export
 * @interface V1alpha1CPUPreferences
 */
export interface V1alpha1CPUPreferences {
  /**
   * PreferredCPUTopology optionally defines the preferred guest visible CPU topology, defaults to PreferSockets.
   * @type {string}
   * @memberof V1alpha1CPUPreferences
   */
  preferredCPUTopology?: string;
}

export function V1alpha1CPUPreferencesFromJSON(json: any): V1alpha1CPUPreferences {
  return V1alpha1CPUPreferencesFromJSONTyped(json, false);
}

export function V1alpha1CPUPreferencesFromJSONTyped(
  json: any,
  _ignoreDiscriminator: boolean,
): V1alpha1CPUPreferences {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    preferredCPUTopology: !exists(json, 'preferredCPUTopology')
      ? undefined
      : json['preferredCPUTopology'],
  };
}

export function V1alpha1CPUPreferencesToJSON(value?: V1alpha1CPUPreferences | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    preferredCPUTopology: value.preferredCPUTopology,
  };
}
