/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    K8sIoApimachineryPkgApisMetaV1ObjectMeta,
    V1alpha1VirtualMachinePoolSpec,
    V1alpha1VirtualMachinePoolStatus,
} from './';

/**
 * VirtualMachinePool resource contains a VirtualMachine configuration that can be used to replicate multiple VirtualMachine resources.
 * @export
 * @interface V1alpha1VirtualMachinePool
 */
export interface V1alpha1VirtualMachinePool {
    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     * @type {string}
     * @memberof V1alpha1VirtualMachinePool
     */
    apiVersion?: string;
    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     * @type {string}
     * @memberof V1alpha1VirtualMachinePool
     */
    kind?: string;
    /**
     * 
     * @type {K8sIoApimachineryPkgApisMetaV1ObjectMeta}
     * @memberof V1alpha1VirtualMachinePool
     */
    metadata?: K8sIoApimachineryPkgApisMetaV1ObjectMeta;
    /**
     * 
     * @type {V1alpha1VirtualMachinePoolSpec}
     * @memberof V1alpha1VirtualMachinePool
     */
    spec: V1alpha1VirtualMachinePoolSpec;
    /**
     * 
     * @type {V1alpha1VirtualMachinePoolStatus}
     * @memberof V1alpha1VirtualMachinePool
     */
    status?: V1alpha1VirtualMachinePoolStatus;
}
