/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
/**
 *
 * @export
 * @interface V1alpha1VirtualMachinePoolNameGeneration
 */
export interface V1alpha1VirtualMachinePoolNameGeneration {
  /**
   *
   * @type {boolean}
   * @memberof V1alpha1VirtualMachinePoolNameGeneration
   */
  appendIndexToConfigMapRefs?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof V1alpha1VirtualMachinePoolNameGeneration
   */
  appendIndexToSecretRefs?: boolean;
}

export function V1alpha1VirtualMachinePoolNameGenerationFromJSON(
  json: any,
): V1alpha1VirtualMachinePoolNameGeneration {
  return V1alpha1VirtualMachinePoolNameGenerationFromJSONTyped(json, false);
}

export function V1alpha1VirtualMachinePoolNameGenerationFromJSONTyped(
  json: any,
  _ignoreDiscriminator: boolean,
): V1alpha1VirtualMachinePoolNameGeneration {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    appendIndexToConfigMapRefs: !exists(json, 'appendIndexToConfigMapRefs')
      ? undefined
      : json['appendIndexToConfigMapRefs'],
    appendIndexToSecretRefs: !exists(json, 'appendIndexToSecretRefs')
      ? undefined
      : json['appendIndexToSecretRefs'],
  };
}

export function V1alpha1VirtualMachinePoolNameGenerationToJSON(
  value?: V1alpha1VirtualMachinePoolNameGeneration | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    appendIndexToConfigMapRefs: value.appendIndexToConfigMapRefs,
    appendIndexToSecretRefs: value.appendIndexToSecretRefs,
  };
}
