/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V1alpha1VirtualMachineExportLink,
    V1alpha1VirtualMachineExportLinkFromJSON,
    V1alpha1VirtualMachineExportLinkFromJSONTyped,
    V1alpha1VirtualMachineExportLinkToJSON,
} from './';

/**
 * VirtualMachineExportLinks contains the links that point the exported VM resources
 * @export
 * @interface V1alpha1VirtualMachineExportLinks
 */
export interface V1alpha1VirtualMachineExportLinks {
    /**
     * 
     * @type {V1alpha1VirtualMachineExportLink}
     * @memberof V1alpha1VirtualMachineExportLinks
     */
    external?: V1alpha1VirtualMachineExportLink;
    /**
     * 
     * @type {V1alpha1VirtualMachineExportLink}
     * @memberof V1alpha1VirtualMachineExportLinks
     */
    internal?: V1alpha1VirtualMachineExportLink;
}

export function V1alpha1VirtualMachineExportLinksFromJSON(json: any): V1alpha1VirtualMachineExportLinks {
    return V1alpha1VirtualMachineExportLinksFromJSONTyped(json, false);
}

export function V1alpha1VirtualMachineExportLinksFromJSONTyped(json: any, _ignoreDiscriminator: boolean): V1alpha1VirtualMachineExportLinks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'external': !exists(json, 'external') ? undefined : V1alpha1VirtualMachineExportLinkFromJSON(json['external']),
        'internal': !exists(json, 'internal') ? undefined : V1alpha1VirtualMachineExportLinkFromJSON(json['internal']),
    };
}

export function V1alpha1VirtualMachineExportLinksToJSON(value?: V1alpha1VirtualMachineExportLinks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'external': V1alpha1VirtualMachineExportLinkToJSON(value.external),
        'internal': V1alpha1VirtualMachineExportLinkToJSON(value.internal),
    };
}

