/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { V1beta1VirtualMachine } from './V1beta1VirtualMachine';
/**
 * SourceSpec contains the appropriate spec for the resource being snapshotted
 * @export
 * @interface V1beta1SourceSpec
 */
export interface V1beta1SourceSpec {
  /**
   *
   * @type {V1beta1VirtualMachine}
   * @memberof V1beta1SourceSpec
   */
  virtualMachine?: V1beta1VirtualMachine;
}

/**
 * Check if a given object implements the V1beta1SourceSpec interface.
 */
