/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { V1CPUFeature } from './V1CPUFeature';
import type { V1beta1SpreadOptions } from './V1beta1SpreadOptions';
/**
 * CPUPreferences contains various optional CPU preferences.
 * @export
 * @interface V1beta1CPUPreferences
 */
export interface V1beta1CPUPreferences {
  /**
   * PreferredCPUFeatures optionally defines a slice of preferred CPU features.
   * @type {Array<V1CPUFeature>}
   * @memberof V1beta1CPUPreferences
   */
  preferredCPUFeatures?: Array<V1CPUFeature>;
  /**
   * PreferredCPUTopology optionally defines the preferred guest visible CPU topology, defaults to PreferSockets.
   * @type {string}
   * @memberof V1beta1CPUPreferences
   */
  preferredCPUTopology?: string;
  /**
   *
   * @type {V1beta1SpreadOptions}
   * @memberof V1beta1CPUPreferences
   */
  spreadOptions?: V1beta1SpreadOptions;
}

/**
 * Check if a given object implements the V1beta1CPUPreferences interface.
 */
