/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * DataVolumeSourceRef defines an indirect reference to the source of data for the DataVolume
 * @export
 * @interface V1beta1DataVolumeSourceRef
 */
export interface V1beta1DataVolumeSourceRef {
  /**
   * The kind of the source reference, currently only "DataSource" is supported
   * @type {string}
   * @memberof V1beta1DataVolumeSourceRef
   */
  kind: string;
  /**
   * The name of the source reference
   * @type {string}
   * @memberof V1beta1DataVolumeSourceRef
   */
  name: string;
  /**
   * The namespace of the source reference, defaults to the DataVolume namespace
   * @type {string}
   * @memberof V1beta1DataVolumeSourceRef
   */
  namespace?: string;
}

/**
 * Check if a given object implements the V1beta1DataVolumeSourceRef interface.
 */
