/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { V1beta1VirtualMachineExportVolumeFormat } from './V1beta1VirtualMachineExportVolumeFormat';
/**
 * VirtualMachineExportVolume contains the name and available formats for the exported volume
 * @export
 * @interface V1beta1VirtualMachineExportVolume
 */
export interface V1beta1VirtualMachineExportVolume {
  /**
   *
   * @type {Array<V1beta1VirtualMachineExportVolumeFormat>}
   * @memberof V1beta1VirtualMachineExportVolume
   */
  formats?: Array<V1beta1VirtualMachineExportVolumeFormat>;
  /**
   * Name is the name of the exported volume
   * @type {string}
   * @memberof V1beta1VirtualMachineExportVolume
   */
  name: string;
}

/**
 * Check if a given object implements the V1beta1VirtualMachineExportVolume interface.
 */
