/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface V1beta1VolumePreferences
 */
export interface V1beta1VolumePreferences {
  /**
   * PreffereedStorageClassName optionally defines the preferred storageClass
   * @type {string}
   * @memberof V1beta1VolumePreferences
   */
  preferredStorageClassName?: string;
}

/**
 * Check if a given object implements the V1beta1VolumePreferences interface.
 */
