/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { V1beta1VirtualMachinePoolSelectionPolicy } from './V1beta1VirtualMachinePoolSelectionPolicy';
/**
 * VirtualMachinePoolProactiveScaleInStrategy represents proactive scale-in strategy
 * @export
 * @interface V1beta1VirtualMachinePoolProactiveScaleInStrategy
 */
export interface V1beta1VirtualMachinePoolProactiveScaleInStrategy {
  /**
   *
   * @type {V1beta1VirtualMachinePoolSelectionPolicy}
   * @memberof V1beta1VirtualMachinePoolProactiveScaleInStrategy
   */
  selectionPolicy?: V1beta1VirtualMachinePoolSelectionPolicy;
  /**
   * Specifies if and how to preserve the state of the VMs selected during scale-in. Disabled - (Default) all state for VMs selected for scale-in will be deleted. Offline - PVCs for VMs selected for scale-in will be preserved and reused on scale-out (decreases provisioning time during scale out). Online - PVCs and memory for VMs selected for scale-in will be preserved and reused on scale-out (decreases provisioning and boot time during scale out).
   * @type {string}
   * @memberof V1beta1VirtualMachinePoolProactiveScaleInStrategy
   */
  statePreservation?: string;
}

/**
 * Check if a given object implements the V1beta1VirtualMachinePoolProactiveScaleInStrategy interface.
 */
