/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { V1beta1VirtualMachinePoolCondition } from './V1beta1VirtualMachinePoolCondition';
/**
 *
 * @export
 * @interface V1beta1VirtualMachinePoolStatus
 */
export interface V1beta1VirtualMachinePoolStatus {
  /**
   *
   * @type {Array<V1beta1VirtualMachinePoolCondition>}
   * @memberof V1beta1VirtualMachinePoolStatus
   */
  conditions?: Array<V1beta1VirtualMachinePoolCondition>;
  /**
   * Canonical form of the label selector for HPA which consumes it through the scale subresource.
   * @type {string}
   * @memberof V1beta1VirtualMachinePoolStatus
   */
  labelSelector?: string;
  /**
   *
   * @type {number}
   * @memberof V1beta1VirtualMachinePoolStatus
   */
  readyReplicas?: number;
  /**
   *
   * @type {number}
   * @memberof V1beta1VirtualMachinePoolStatus
   */
  replicas?: number;
}

/**
 * Check if a given object implements the V1beta1VirtualMachinePoolStatus interface.
 */
