/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { K8sIoApiCoreV1TypedLocalObjectReference } from './K8sIoApiCoreV1TypedLocalObjectReference';
import type { K8sIoApiCoreV1TypedObjectReference } from './K8sIoApiCoreV1TypedObjectReference';
import type { K8sIoApiCoreV1VolumeResourceRequirements } from './K8sIoApiCoreV1VolumeResourceRequirements';
import type { K8sIoApimachineryPkgApisMetaV1LabelSelector } from './K8sIoApimachineryPkgApisMetaV1LabelSelector';
/**
 * StorageSpec defines the Storage type specification
 * @export
 * @interface V1beta1StorageSpec
 */
export interface V1beta1StorageSpec {
  /**
   * AccessModes contains the desired access modes the volume should have. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1
   * @type {Array<string>}
   * @memberof V1beta1StorageSpec
   */
  accessModes?: Array<V1beta1StorageSpecAccessModesEnum>;
  /**
   *
   * @type {K8sIoApiCoreV1TypedLocalObjectReference}
   * @memberof V1beta1StorageSpec
   */
  dataSource?: K8sIoApiCoreV1TypedLocalObjectReference;
  /**
   *
   * @type {K8sIoApiCoreV1TypedObjectReference}
   * @memberof V1beta1StorageSpec
   */
  dataSourceRef?: K8sIoApiCoreV1TypedObjectReference;
  /**
   *
   * @type {K8sIoApiCoreV1VolumeResourceRequirements}
   * @memberof V1beta1StorageSpec
   */
  resources?: K8sIoApiCoreV1VolumeResourceRequirements;
  /**
   *
   * @type {K8sIoApimachineryPkgApisMetaV1LabelSelector}
   * @memberof V1beta1StorageSpec
   */
  selector?: K8sIoApimachineryPkgApisMetaV1LabelSelector;
  /**
   * Name of the StorageClass required by the claim. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#class-1
   * @type {string}
   * @memberof V1beta1StorageSpec
   */
  storageClassName?: string;
  /**
   * volumeMode defines what type of volume is required by the claim. Value of Filesystem is implied when not included in claim spec.
   *
   * Possible enum values:
   *  - `"Block"` means the volume will not be formatted with a filesystem and will remain a raw block device.
   *  - `"Filesystem"` means the volume will be or is formatted with a filesystem.
   *  - `"FromStorageProfile"` means the volume mode will be auto selected by CDI according to a matching StorageProfile
   * @type {string}
   * @memberof V1beta1StorageSpec
   */
  volumeMode?: V1beta1StorageSpecVolumeModeEnum;
  /**
   * VolumeName is the binding reference to the PersistentVolume backing this claim.
   * @type {string}
   * @memberof V1beta1StorageSpec
   */
  volumeName?: string;
}

/**
 * @export
 */
export const V1beta1StorageSpecAccessModesEnum = {
  ReadOnlyMany: 'ReadOnlyMany',
  ReadWriteMany: 'ReadWriteMany',
  ReadWriteOnce: 'ReadWriteOnce',
  ReadWriteOncePod: 'ReadWriteOncePod',
} as const;
export type V1beta1StorageSpecAccessModesEnum =
  typeof V1beta1StorageSpecAccessModesEnum[keyof typeof V1beta1StorageSpecAccessModesEnum];

/**
 * @export
 */
export const V1beta1StorageSpecVolumeModeEnum = {
  Block: 'Block',
  Filesystem: 'Filesystem',
  FromStorageProfile: 'FromStorageProfile',
} as const;
export type V1beta1StorageSpecVolumeModeEnum =
  typeof V1beta1StorageSpecVolumeModeEnum[keyof typeof V1beta1StorageSpecVolumeModeEnum];

/**
 * Check if a given object implements the V1beta1StorageSpec interface.
 */
