/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { V1ClockOffsetUTC } from './V1ClockOffsetUTC';
import type { V1Timer } from './V1Timer';
/**
 * Represents the clock and timers of a vmi.
 * @export
 * @interface V1Clock
 */
export interface V1Clock {
  /**
   *
   * @type {V1Timer}
   * @memberof V1Clock
   */
  timer?: V1Timer;
  /**
   * Timezone sets the guest clock to the specified timezone. Zone name follows the TZ environment variable format (e.g. 'America/New_York').
   * @type {string}
   * @memberof V1Clock
   */
  timezone?: string;
  /**
   *
   * @type {V1ClockOffsetUTC}
   * @memberof V1Clock
   */
  utc?: V1ClockOffsetUTC;
}

/**
 * Check if a given object implements the V1Clock interface.
 */
