/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * CustomBlockSize represents the desired logical and physical block size for a VM disk.
 * @export
 * @interface V1CustomBlockSize
 */
export interface V1CustomBlockSize {
    /**
     * 
     * @type {number}
     * @memberof V1CustomBlockSize
     */
    logical: number;
    /**
     * 
     * @type {number}
     * @memberof V1CustomBlockSize
     */
    physical: number;
}

export function V1CustomBlockSizeFromJSON(json: any): V1CustomBlockSize {
    return V1CustomBlockSizeFromJSONTyped(json, false);
}

export function V1CustomBlockSizeFromJSONTyped(json: any, _ignoreDiscriminator: boolean): V1CustomBlockSize {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'logical': json['logical'],
        'physical': json['physical'],
    };
}

export function V1CustomBlockSizeToJSON(value?: V1CustomBlockSize | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'logical': value.logical,
        'physical': value.physical,
    };
}

