/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface V1CustomizeComponentsPatch
 */
export interface V1CustomizeComponentsPatch {
  /**
   *
   * @type {string}
   * @memberof V1CustomizeComponentsPatch
   */
  patch: string;
  /**
   *
   * @type {string}
   * @memberof V1CustomizeComponentsPatch
   */
  resourceName: string;
  /**
   *
   * @type {string}
   * @memberof V1CustomizeComponentsPatch
   */
  resourceType: string;
  /**
   *
   * @type {string}
   * @memberof V1CustomizeComponentsPatch
   */
  type: string;
}

/**
 * Check if a given object implements the V1CustomizeComponentsPatch interface.
 */
