/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { V1DeviceStatusInfo } from './V1DeviceStatusInfo';
/**
 * DeviceStatus has the information of all devices allocated spec.domain.devices
 * @export
 * @interface V1DeviceStatus
 */
export interface V1DeviceStatus {
  /**
   * GPUStatuses reflects the state of GPUs requested in spec.domain.devices.gpus
   * @type {Array<V1DeviceStatusInfo>}
   * @memberof V1DeviceStatus
   */
  gpuStatuses?: Array<V1DeviceStatusInfo>;
  /**
   * HostDeviceStatuses reflects the state of GPUs requested in spec.domain.devices.hostDevices DRA
   * @type {Array<V1DeviceStatusInfo>}
   * @memberof V1DeviceStatus
   */
  hostDeviceStatuses?: Array<V1DeviceStatusInfo>;
}

/**
 * Check if a given object implements the V1DeviceStatus interface.
 */
