/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { V1CPU } from './V1CPU';
import type { V1Chassis } from './V1Chassis';
import type { V1Clock } from './V1Clock';
import type { V1Devices } from './V1Devices';
import type { V1DiskIOThreads } from './V1DiskIOThreads';
import type { V1Features } from './V1Features';
import type { V1Firmware } from './V1Firmware';
import type { V1LaunchSecurity } from './V1LaunchSecurity';
import type { V1Machine } from './V1Machine';
import type { V1Memory } from './V1Memory';
import type { V1ResourceRequirements } from './V1ResourceRequirements';
/**
 *
 * @export
 * @interface V1DomainSpec
 */
export interface V1DomainSpec {
  /**
   *
   * @type {V1Chassis}
   * @memberof V1DomainSpec
   */
  chassis?: V1Chassis;
  /**
   *
   * @type {V1Clock}
   * @memberof V1DomainSpec
   */
  clock?: V1Clock;
  /**
   *
   * @type {V1CPU}
   * @memberof V1DomainSpec
   */
  cpu?: V1CPU;
  /**
   *
   * @type {V1Devices}
   * @memberof V1DomainSpec
   */
  devices: V1Devices;
  /**
   *
   * @type {V1Features}
   * @memberof V1DomainSpec
   */
  features?: V1Features;
  /**
   *
   * @type {V1Firmware}
   * @memberof V1DomainSpec
   */
  firmware?: V1Firmware;
  /**
   *
   * @type {V1DiskIOThreads}
   * @memberof V1DomainSpec
   */
  ioThreads?: V1DiskIOThreads;
  /**
   * Controls whether or not disks will share IOThreads. Omitting IOThreadsPolicy disables use of IOThreads. One of: shared, auto, supplementalPool
   * @type {string}
   * @memberof V1DomainSpec
   */
  ioThreadsPolicy?: string;
  /**
   *
   * @type {V1LaunchSecurity}
   * @memberof V1DomainSpec
   */
  launchSecurity?: V1LaunchSecurity;
  /**
   *
   * @type {V1Machine}
   * @memberof V1DomainSpec
   */
  machine?: V1Machine;
  /**
   *
   * @type {V1Memory}
   * @memberof V1DomainSpec
   */
  memory?: V1Memory;
  /**
   *
   * @type {V1ResourceRequirements}
   * @memberof V1DomainSpec
   */
  resources?: V1ResourceRequirements;
}

/**
 * Check if a given object implements the V1DomainSpec interface.
 */
