/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { V1DataVolumeSource } from './V1DataVolumeSource';
import type { V1PersistentVolumeClaimVolumeSource } from './V1PersistentVolumeClaimVolumeSource';
/**
 * HotplugVolumeSource Represents the source of a volume to mount which are capable of being hotplugged on a live running VMI. Only one of its members may be specified.
 * @export
 * @interface V1HotplugVolumeSource
 */
export interface V1HotplugVolumeSource {
  /**
   *
   * @type {V1DataVolumeSource}
   * @memberof V1HotplugVolumeSource
   */
  dataVolume?: V1DataVolumeSource;
  /**
   *
   * @type {V1PersistentVolumeClaimVolumeSource}
   * @memberof V1HotplugVolumeSource
   */
  persistentVolumeClaim?: V1PersistentVolumeClaimVolumeSource;
}

/**
 * Check if a given object implements the V1HotplugVolumeSource interface.
 */
