/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { V1ControllerRevisionRef } from './V1ControllerRevisionRef';
/**
 *
 * @export
 * @interface V1InstancetypeStatusRef
 */
export interface V1InstancetypeStatusRef {
  /**
   *
   * @type {V1ControllerRevisionRef}
   * @memberof V1InstancetypeStatusRef
   */
  controllerRevisionRef?: V1ControllerRevisionRef;
  /**
   * InferFromVolume lists the name of a volume that should be used to infer or discover the resource
   * @type {string}
   * @memberof V1InstancetypeStatusRef
   */
  inferFromVolume?: string;
  /**
   * InferFromVolumeFailurePolicy controls what should happen on failure when inferring the resource
   * @type {string}
   * @memberof V1InstancetypeStatusRef
   */
  inferFromVolumeFailurePolicy?: string;
  /**
   * Kind specifies the kind of resource
   * @type {string}
   * @memberof V1InstancetypeStatusRef
   */
  kind?: string;
  /**
   * Name is the name of resource
   * @type {string}
   * @memberof V1InstancetypeStatusRef
   */
  name?: string;
}

/**
 * Check if a given object implements the V1InstancetypeStatusRef interface.
 */
