/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface V1QemuGuestAgentSSHPublicKeyAccessCredentialPropagation
 */
export interface V1QemuGuestAgentSSHPublicKeyAccessCredentialPropagation {
  /**
   * Users represents a list of guest users that should have the ssh public keys added to their authorized_keys file.
   * @type {Array<string>}
   * @memberof V1QemuGuestAgentSSHPublicKeyAccessCredentialPropagation
   */
  users: Array<string>;
}

/**
 * Check if a given object implements the V1QemuGuestAgentSSHPublicKeyAccessCredentialPropagation interface.
 */
