/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { V1RateLimiter } from './V1RateLimiter';
/**
 * RESTClientConfiguration allows configuring certain aspects of the k8s rest client.
 * @export
 * @interface V1RESTClientConfiguration
 */
export interface V1RESTClientConfiguration {
  /**
   *
   * @type {V1RateLimiter}
   * @memberof V1RESTClientConfiguration
   */
  rateLimiter?: V1RateLimiter;
}

/**
 * Check if a given object implements the V1RESTClientConfiguration interface.
 */
