/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V1SSHPublicKeyAccessCredentialPropagationMethod,
    V1SSHPublicKeyAccessCredentialPropagationMethodFromJSON,
    V1SSHPublicKeyAccessCredentialPropagationMethodFromJSONTyped,
    V1SSHPublicKeyAccessCredentialPropagationMethodToJSON,
    V1SSHPublicKeyAccessCredentialSource,
    V1SSHPublicKeyAccessCredentialSourceFromJSON,
    V1SSHPublicKeyAccessCredentialSourceFromJSONTyped,
    V1SSHPublicKeyAccessCredentialSourceToJSON,
} from './';

/**
 * SSHPublicKeyAccessCredential represents a source and propagation method for injecting ssh public keys into a vm guest
 * @export
 * @interface V1SSHPublicKeyAccessCredential
 */
export interface V1SSHPublicKeyAccessCredential {
    /**
     * 
     * @type {V1SSHPublicKeyAccessCredentialPropagationMethod}
     * @memberof V1SSHPublicKeyAccessCredential
     */
    propagationMethod: V1SSHPublicKeyAccessCredentialPropagationMethod;
    /**
     * 
     * @type {V1SSHPublicKeyAccessCredentialSource}
     * @memberof V1SSHPublicKeyAccessCredential
     */
    source: V1SSHPublicKeyAccessCredentialSource;
}

export function V1SSHPublicKeyAccessCredentialFromJSON(json: any): V1SSHPublicKeyAccessCredential {
    return V1SSHPublicKeyAccessCredentialFromJSONTyped(json, false);
}

export function V1SSHPublicKeyAccessCredentialFromJSONTyped(json: any, _ignoreDiscriminator: boolean): V1SSHPublicKeyAccessCredential {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'propagationMethod': V1SSHPublicKeyAccessCredentialPropagationMethodFromJSON(json['propagationMethod']),
        'source': V1SSHPublicKeyAccessCredentialSourceFromJSON(json['source']),
    };
}

export function V1SSHPublicKeyAccessCredentialToJSON(value?: V1SSHPublicKeyAccessCredential | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'propagationMethod': V1SSHPublicKeyAccessCredentialPropagationMethodToJSON(value.propagationMethod),
        'source': V1SSHPublicKeyAccessCredentialSourceToJSON(value.source),
    };
}

