/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface V1TPMDevice
 */
export interface V1TPMDevice {
  /**
   * Enabled allows a user to explicitly disable the vTPM even when one is enabled by a preference referenced by the VirtualMachine Defaults to True
   * @type {boolean}
   * @memberof V1TPMDevice
   */
  enabled?: boolean;
  /**
   * Persistent indicates the state of the TPM device should be kept accross reboots Defaults to false
   * @type {boolean}
   * @memberof V1TPMDevice
   */
  persistent?: boolean;
}

/**
 * Check if a given object implements the V1TPMDevice interface.
 */
