/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface V1VirtualMachineStateChangeRequest
 */
export interface V1VirtualMachineStateChangeRequest {
  /**
   * Indicates the type of action that is requested. e.g. Start or Stop
   * @type {string}
   * @memberof V1VirtualMachineStateChangeRequest
   */
  action: string;
  /**
   * Provides additional data in order to perform the Action
   * @type {{ [key: string]: string; }}
   * @memberof V1VirtualMachineStateChangeRequest
   */
  data?: { [key: string]: string };
  /**
   * Indicates the UUID of an existing Virtual Machine Instance that this change request applies to -- if applicable
   * @type {string}
   * @memberof V1VirtualMachineStateChangeRequest
   */
  uid?: string;
}

/**
 * Check if a given object implements the V1VirtualMachineStateChangeRequest interface.
 */
