/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { V1AddVolumeOptions } from './V1AddVolumeOptions';
import type { V1RemoveVolumeOptions } from './V1RemoveVolumeOptions';
/**
 *
 * @export
 * @interface V1VirtualMachineVolumeRequest
 */
export interface V1VirtualMachineVolumeRequest {
  /**
   *
   * @type {V1AddVolumeOptions}
   * @memberof V1VirtualMachineVolumeRequest
   */
  addVolumeOptions?: V1AddVolumeOptions;
  /**
   *
   * @type {V1RemoveVolumeOptions}
   * @memberof V1VirtualMachineVolumeRequest
   */
  removeVolumeOptions?: V1RemoveVolumeOptions;
}

/**
 * Check if a given object implements the V1VirtualMachineVolumeRequest interface.
 */
