/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { K8sIoApimachineryPkgApisMetaV1LabelSelector } from './K8sIoApimachineryPkgApisMetaV1LabelSelector';
import type { V1DomainSpec } from './V1DomainSpec';
/**
 *
 * @export
 * @interface V1VirtualMachineInstancePresetSpec
 */
export interface V1VirtualMachineInstancePresetSpec {
  /**
   *
   * @type {V1DomainSpec}
   * @memberof V1VirtualMachineInstancePresetSpec
   */
  domain?: V1DomainSpec;
  /**
   *
   * @type {K8sIoApimachineryPkgApisMetaV1LabelSelector}
   * @memberof V1VirtualMachineInstancePresetSpec
   */
  selector: K8sIoApimachineryPkgApisMetaV1LabelSelector;
}

/**
 * Check if a given object implements the V1VirtualMachineInstancePresetSpec interface.
 */
