/* tslint:disable */
/* eslint-disable */
/**
 * KubeVirt API
 * This is KubeVirt API an add-on for Kubernetes.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kubevirt-dev@googlegroups.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface V1VirtualMachineInstanceMigrationSource
 */
export interface V1VirtualMachineInstanceMigrationSource {
  /**
   * The synchronization controller URL to connect to.
   * @type {string}
   * @memberof V1VirtualMachineInstanceMigrationSource
   */
  connectURL: string;
  /**
   * A unique identifier to identify this migration.
   * @type {string}
   * @memberof V1VirtualMachineInstanceMigrationSource
   */
  migrationID: string;
}

/**
 * Check if a given object implements the V1VirtualMachineInstanceMigrationSource interface.
 */
